import { UserRole, ArticleStatus, Language } from './types';

export const ROLES: UserRole[] = [UserRole.CLIENT, UserRole.JOURNAL_MANAGER, UserRole.ACCOUNTANT, UserRole.ADMIN];
export const ARTICLE_STATUSES: ArticleStatus[] = [
  ArticleStatus.PENDING,
  ArticleStatus.REVIEWING,
  ArticleStatus.NEEDS_REVISION,
  ArticleStatus.ACCEPTED,
  ArticleStatus.REJECTED,
  ArticleStatus.PUBLISHED, 
];

export const DEFAULT_LANGUAGE: Language = Language.UZ; 
export const SUPPORTED_LANGUAGES: Language[] = [Language.UZ]; 

export const GEMINI_TEXT_MODEL = 'gemini-2.5-flash-preview-04-17';
export const GEMINI_IMAGE_MODEL = 'imagen-3.0-generate-002';

export const MOCK_API_DELAY = 1000; 
export const PLAGIARISM_CERTIFICATE_THRESHOLD = 15; // Threshold for certificate eligibility
export const AI_CONTENT_CERTIFICATE_THRESHOLD = 30; // Threshold for AI content probability for certificate
export const MOCK_PLAGIARISM_CHECK_PRICE = "30,000"; // Mock price
export const MOCK_ARTICLE_SUBMISSION_PRICE = "50,000"; // New: Mock price for article submission
export const MOCK_PLASTIC_CARD_NUMBER = "8600 1234 5678 9012"; // Added mock plastic card number

export const LocalizationKeys = {
  APP_TITLE_FULL: 'app_title_full_pspc',
  APP_TITLE_SHORT: 'app_title_short_pspc',
  MANAGE_JOURNAL_ISSUES_BUTTON: 'manage_journal_issues_button',
  JOURNAL_ISSUE_MANAGEMENT_TITLE: 'journal_issue_management_title',
  CREATE_NEW_ISSUE_BUTTON: 'create_new_issue_button',
  ISSUE_NUMBER_LABEL: 'issue_number_label',
  ISSUE_NUMBER_PLACEHOLDER: 'issue_number_placeholder',
  PUBLICATION_DATE_LABEL: 'publication_date_label',
  COVER_IMAGE_URL_LABEL: 'cover_image_url_label',
  COVER_IMAGE_URL_PLACEHOLDER: 'cover_image_url_placeholder',
  COMPILED_ISSUE_PDF_URL_LABEL: 'compiled_issue_pdf_url_label',
  COMPILED_ISSUE_PDF_URL_PLACEHOLDER: 'compiled_issue_pdf_url_placeholder',
  IS_PUBLISHED_LABEL: 'is_published_label',
  CREATE_ISSUE_MODAL_TITLE: 'create_issue_modal_title',
  EDIT_ISSUE_MODAL_TITLE: 'edit_issue_modal_title',
  ISSUE_CREATED_SUCCESS: 'issue_created_success',
  ISSUE_UPDATED_SUCCESS: 'issue_updated_success',
  NO_ISSUES_FOUND: 'no_issues_found',
  VIEW_ISSUE_DETAILS_BUTTON: 'view_issue_details_button',
  ARTICLES_IN_ISSUE_LABEL: 'articles_in_issue_label',
  PUBLISHED_IN_ISSUE_LABEL: 'published_in_issue_label',
  DOWNLOAD_ISSUE_BUTTON: 'download_issue_button', 
  AI_TITLE_SUGGESTION_TITLE: 'ai_title_suggestion_title',
  GET_TITLE_SUGGESTIONS_BUTTON: 'get_title_suggestions_button',
  SUGGESTED_TITLES_LABEL: 'suggested_titles_label',
  AI_SUGGESTING_TITLES: 'ai_suggesting_titles',
  AI_ERROR_NO_TITLE_SUGGESTIONS: 'ai_error_no_title_suggestions',
  PRELIMINARY_PLAGIARISM_CHECK: 'preliminary_plagiarism_check',
  RUN_PLAGIARISM_CHECK_BUTTON: 'run_plagiarism_check_button',
  PLAGIARISM_CHECK_RESULT: 'plagiarism_check_result',
  SIMILARITY_PERCENTAGE: 'similarity_percentage',
  VIEW_PLAGIARISM_REPORT: 'view_plagiarism_report',
  AI_JOURNAL_SUGGESTION_TITLE: 'ai_journal_suggestion_title',
  GET_JOURNAL_SUGGESTIONS_BUTTON: 'get_journal_suggestions_button',
  SUGGESTED_JOURNALS: 'suggested_journals',
  REASONING: 'reasoning',
  AI_REFERENCE_CHECK_TITLE: 'ai_reference_check_title',
  CHECK_REFERENCES_BUTTON: 'check_references_button',
  REFERENCE_ANALYSIS_RESULT: 'reference_analysis_result',
  AI_ABSTRACT_HELP_TITLE: 'ai_abstract_help_title',
  IMPROVE_ABSTRACT_BUTTON: 'improve_abstract_button',
  GENERATE_ABSTRACT_SNIPPET_BUTTON: 'generate_abstract_snippet_button',
  AI_SUGGESTED_ABSTRACT: 'ai_suggested_abstract',
  COMPARE_VERSIONS_BUTTON: 'compare_versions_button',
  COAUTHOR_CONTRIBUTION_SHARE_LABEL: 'coauthor_contribution_share_label',
  COAUTHOR_CONTRIBUTION_SHARE_PLACEHOLDER: 'coauthor_contribution_share_placeholder',
  ARTICLE_NOTES_TITLE: 'article_notes_title',
  ADD_NOTE_BUTTON: 'add_note_button',
  ARTICLE_TAGS_TITLE: 'article_tags_title',
  ADD_TAG_BUTTON: 'add_tag_button',
  NO_NOTES_YET: 'no_notes_yet',
  NO_TAGS_YET: 'no_tags_yet',
  JOURNAL_SUBMISSION_CHECKLIST_TITLE: 'journal_submission_checklist_title',
  NOTIFICATION_PREFERENCES_TITLE: 'notification_preferences_title',
  NOTIFY_STATUS_CHANGE: 'notify_status_change', 
  NOTIFY_NEW_MESSAGE: 'notify_new_message',
  NOTIFY_DEADLINE_REMINDER: 'notify_deadline_reminder',
  DOWNLOAD_ACCEPTANCE_CERTIFICATE_BUTTON: 'download_acceptance_certificate_button',
  CERTIFICATE_GENERATION_PROMPT: 'certificate_generation_prompt',
  AI_ERROR_NO_JOURNAL_SUGGESTIONS: 'ai_error_no_journal_suggestions',
  AI_ERROR_REFERENCE_ANALYSIS: 'ai_error_reference_analysis',
  AI_ERROR_ABSTRACT_HELP: 'ai_error_abstract_help',
  VERSION_COMPARISON_UNAVAILABLE: 'version_comparison_unavailable',
  NOTES_SAVE_SUCCESS: 'notes_save_success',
  TAGS_SAVE_SUCCESS: 'tags_save_success',
  CHECKLIST_NOT_AVAILABLE: 'checklist_not_available',
  ENTER_NOTE_PLACEHOLDER: 'enter_note_placeholder',
  ENTER_TAG_PLACEHOLDER: 'enter_tag_placeholder',
  PLAGIARISM_CHECK_RUNNING: 'plagiarism_check_running',
  AI_ANALYZING_REFERENCES: 'ai_analyzing_references',
  AI_IMPROVING_ABSTRACT: 'ai_improving_abstract',
  AI_SUGGESTING_JOURNALS: 'ai_suggesting_journals',
  API_KEY_REQUIRED_FOR_AI_FEATURE: 'api_key_required_for_ai_feature',
  ADMIN_DASHBOARD_TITLE: 'admin_dashboard_title',
  SYSTEM_HEALTH_TITLE: 'system_health_title',
  DATABASE_STATUS_LABEL: 'database_status_label',
  API_SERVICE_STATUS_LABEL: 'api_service_status_label',
  STORAGE_USAGE_LABEL: 'storage_usage_label',
  LAST_BACKUP_LABEL: 'last_backup_label',
  INTEGRATION_STATUS_TITLE: 'integration_status_title',
  AI_GEMINI_SERVICE_LABEL: 'ai_gemini_service_label',
  PLAGIARISM_CHECKER_SERVICE_LABEL: 'plagiarism_checker_service_label',
  DOI_PROVIDER_SERVICE_LABEL: 'doi_provider_service_label', // Feature 1
  KEY_SET_LABEL: 'key_set_label',
  KEY_NOT_SET_LABEL: 'key_not_set_label',
  LAST_CHECKED_LABEL: 'last_checked_label',
  STUCK_ARTICLES_TITLE: 'stuck_articles_title',
  VIEW_STUCK_ARTICLES_BUTTON: 'view_stuck_articles_button',
  NO_STUCK_ARTICLES_MESSAGE: 'no_stuck_articles_message',
  USER_MANAGEMENT_BULK_ACTIONS_LABEL: 'user_management_bulk_actions_label',
  SELECT_ACTION_LABEL: 'select_action_label',
  DEACTIVATE_SELECTED_ACTION: 'deactivate_selected_action',
  ACTIVATE_SELECTED_ACTION: 'activate_selected_action',
  ASSIGN_ROLE_SELECTED_ACTION: 'assign_role_selected_action',
  APPLY_BULK_ACTION_BUTTON: 'apply_bulk_action_button',
  SELECT_USERS_FOR_BULK_ACTION_PROMPT: 'select_users_for_bulk_action_prompt',
  BULK_ACTION_SUCCESS_MESSAGE: 'bulk_action_success_message',
  JOURNAL_TEMPLATE_MANAGEMENT_TITLE: 'journal_template_management_title',
  SAVE_AS_TEMPLATE_BUTTON: 'save_as_template_button',
  LOAD_FROM_TEMPLATE_BUTTON: 'load_from_template_button',
  NEW_TEMPLATE_NAME_LABEL: 'new_template_name_label',
  NEW_TEMPLATE_NAME_PLACEHOLDER: 'new_template_name_placeholder',
  SELECT_TEMPLATE_LABEL: 'select_template_label',
  TEMPLATE_SAVED_SUCCESS_MESSAGE: 'template_saved_success_message',
  TEMPLATE_LOADED_SUCCESS_MESSAGE: 'template_loaded_success_message',
  TEMPLATE_DELETED_SUCCESS_MESSAGE: 'template_deleted_success_message',
  DELETE_TEMPLATE_BUTTON: 'delete_template_button',
  CONFIRM_DELETE_TEMPLATE_PROMPT: 'confirm_delete_template_prompt',
  SYSTEM_SETTINGS_TITLE_ADMIN: 'system_settings_title_admin',
  NOTIFICATION_TEMPLATE_MANAGEMENT_TITLE: 'notification_template_management_title',
  SELECT_NOTIFICATION_EVENT_LABEL: 'select_notification_event_label',
  SUBJECT_UZ_LABEL: 'subject_uz_label',
  BODY_UZ_LABEL: 'body_uz_label',
  SAVE_NOTIFICATION_TEMPLATE_BUTTON: 'save_notification_template_button',
  NOTIFICATION_TEMPLATE_UPDATED_SUCCESS_MESSAGE: 'notification_template_updated_success_message',
  AVAILABLE_PLACEHOLDERS_LABEL: 'available_placeholders_label',
  INTEGRATION_SETTINGS_TITLE: 'integration_settings_title',
  SERVICE_NAME_LABEL: 'service_name_label',
  API_KEY_MASKED_LABEL: 'api_key_masked_label',
  SET_API_KEY_BUTTON: 'set_api_key_button', 
  SERVICE_ENABLED_LABEL: 'service_enabled_label',
  AI_MODULES_SETTINGS_TITLE: 'ai_modules_settings_title',
  KEYWORD_SUGGESTION_MODULE_LABEL: 'keyword_suggestion_module_label',
  ABSTRACT_IMPROVEMENT_MODULE_LABEL: 'abstract_improvement_module_label',
  JOURNAL_SUGGESTION_MODULE_LABEL: 'journal_suggestion_module_label',
  REFERENCE_CHECKING_MODULE_LABEL: 'reference_checking_module_label',
  TITLE_SUGGESTION_MODULE_LABEL: 'title_suggestion_module_label', 
  JOURNAL_COMPLIANCE_CHECK_MODULE_LABEL: 'journal_compliance_check_module_label', 
  SAVE_INTEGRATION_SETTINGS_BUTTON: 'save_integration_settings_button',
  INTEGRATION_SETTINGS_UPDATED_SUCCESS_MESSAGE: 'integration_settings_updated_success_message',
  GRANULAR_ROLES_TITLE: 'granular_roles_title',
  GRANULAR_ROLES_DESC: 'granular_roles_desc',
  AUDIT_LOG_TITLE: 'audit_log_title',
  FILTER_BY_USER_LABEL: 'filter_by_user_label',
  FILTER_BY_ACTION_TYPE_LABEL: 'filter_by_action_type_label',
  FILTER_BY_DATE_RANGE_LABEL: 'filter_by_date_range_label',
  EXPORT_AUDIT_LOG_BUTTON: 'export_audit_log_button',
  AUDIT_LOG_EXPORTED_MESSAGE: 'audit_log_exported_message',
  NO_AUDIT_LOGS_MESSAGE: 'no_audit_logs_message',
  USER_ID_LABEL: 'user_id_label',
  ACTION_TYPE_LABEL: 'action_type_label',
  TIMESTAMP_LABEL: 'timestamp_label',
  DETAILS_LABEL: 'details_label',
  ARTICLE_OVERVIEW_TITLE_ADMIN: 'article_overview_title_admin',
  FILTER_BY_JOURNAL_LABEL: 'filter_by_journal_label',
  FILTER_BY_AUTHOR_LABEL: 'filter_by_author_label',
  FILTER_BY_STATUS_LABEL: 'filter_by_status_label',
  REASSIGN_EDITOR_BUTTON: 'reassign_editor_button',
  SELECT_NEW_EDITOR_LABEL: 'select_new_editor_label',
  ARTICLE_REASSIGNED_SUCCESS_MESSAGE: 'article_reassigned_success_message',
  NO_ARTICLES_IN_SYSTEM_MESSAGE: 'no_articles_in_system_message',
  DAYS_IN_STATUS_LABEL: 'days_in_status_label',
  ARTICLE_ID_LABEL: 'article_id_label',
  AUTHOR_NAME_LABEL: 'author_name_label',
  ASSIGNED_EDITOR_LABEL: 'assigned_editor_label',
  MAQOLALARNI_BOSHQARISH_ADMIN: 'maqolalarni_boshqarish_admin',
  JURNALLARNI_BOSHQARISH_ADMIN: 'jurnallarni_boshqarish_admin', 
  MENING_JURNALIM: 'mening_jurnalim', 
  AUDIT_JURNALI_ADMIN: 'audit_jurnali_admin',
  GOOGLE_SCHOLAR_METADATA_NOTE: 'google_scholar_metadata_note',
  STATUS_PUBLISHED: 'status_published', 
  ARTICLE_DOI_LABEL: 'article_doi_label',
  ARTICLE_VIEW_COUNT_LABEL: 'article_view_count_label',
  ARTICLE_DOWNLOAD_COUNT_LABEL: 'article_download_count_label',
  ARTICLE_CITATION_COUNT_LABEL: 'article_citation_count_label',
  REVIEWER_COMMENTS_TITLE: 'reviewer_comments_title',
  NO_REVIEWER_COMMENTS_YET: 'no_reviewer_comments_yet',
  REPLY_TO_REVIEWERS_BUTTON: 'reply_to_reviewers_button',
  SUBMIT_REPLY_BUTTON: 'submit_reply_button',
  YOUR_REPLY_PLACEHOLDER: 'your_reply_placeholder',
  REPLY_SUBMITTED_SUCCESS: 'reply_submitted_success',
  FILTER_BY_DOI_LABEL: 'filter_by_doi_label',
  FILTER_BY_PUBLICATION_YEAR_LABEL: 'filter_by_publication_year_label',
  SORT_BY_LABEL: 'sort_by_label',
  SORT_BY_SUBMISSION_DATE: 'sort_by_submission_date',
  SORT_BY_CITATION_COUNT: 'sort_by_citation_count',
  SORT_BY_VIEW_COUNT: 'sort_by_view_count',
  SORT_BY_DOI: 'sort_by_doi',
  AI_JOURNAL_COMPLIANCE_CHECK_TITLE: 'ai_journal_compliance_check_title',
  AI_JOURNAL_COMPLIANCE_CHECK_DESC: 'ai_journal_compliance_check_desc',
  RUN_AI_COMPLIANCE_CHECK_BUTTON: 'run_ai_compliance_check_button',
  AI_COMPLIANCE_CHECK_RUNNING: 'ai_compliance_check_running',
  AI_COMPLIANCE_REPORT_TITLE: 'ai_compliance_report_title',
  AI_COMPLIANCE_ITEM_MET: 'ai_compliance_item_met',
  AI_COMPLIANCE_ITEM_NOT_MET: 'ai_compliance_item_not_met',
  AI_COMPLIANCE_ITEM_NOT_ENOUGH_INFO: 'ai_compliance_item_not_enough_info',
  AI_COMPLIANCE_OVERALL: 'ai_compliance_overall',
  SUBMISSION_TARGET_TYPE_LABEL: 'submission_target_type_label',
  SUBMISSION_TARGET_TYPE_JOURNAL: 'submission_target_type_journal',
  SUBMISSION_TARGET_TYPE_CONFERENCE: 'submission_target_type_conference',
  SUBMISSION_TARGET_TYPE_SPECIAL_ISSUE: 'submission_target_type_special_issue',
  SUBMISSION_TARGET_DETAILS_LABEL: 'submission_target_details_label',
  SUBMISSION_TARGET_DETAILS_PLACEHOLDER: 'submission_target_details_placeholder',
  NOTIFY_ARTICLE_SUBMITTED_CONFIRMATION: 'notify_article_submitted_confirmation',
  NOTIFY_ARTICLE_ASSIGNED_TO_EDITOR: 'notify_article_assigned_to_editor',
  NOTIFY_PEER_REVIEW_STARTED: 'notify_peer_review_started',
  NOTIFY_PEER_REVIEW_COMMENT_RECEIVED: 'notify_peer_review_comment_received',
  NOTIFY_ARTICLE_DECISION_MADE: 'notify_article_decision_made',
  NOTIFY_ARTICLE_PUBLISHED_CONFIRMATION: 'notify_article_published_confirmation',
  NOTIFY_DOI_ASSIGNED_TO_ARTICLE: 'notify_doi_assigned_to_article',
  ALL_SUBMISSION_TARGETS: 'all_submission_targets',
  SUBMITTED_TO_LABEL: 'submitted_to_label',
  ARTICLE_STATS_TITLE: 'article_stats_title',
  JOURNAL_SELECTION_REQUIRED_ERROR: 'journal_selection_required_error',
  DOI_PROVIDER_SETTINGS_TITLE: 'doi_provider_settings_title',
  DOI_PROVIDER_NAME_LABEL: 'doi_provider_name_label',
  DOI_API_KEY_LABEL: 'doi_api_key_label',
  DOI_API_SECRET_LABEL: 'doi_api_secret_label',
  DOI_PREFIX_LABEL: 'doi_prefix_label',
  MANAGE_DOI_TITLE: 'manage_doi_title',
  ASSIGN_GENERATE_DOI_BUTTON: 'assign_generate_doi_button',
  DOI_ASSIGNED_SUCCESS: 'doi_assigned_success',
  DOI_STATUS_LABEL: 'doi_status_label',
  PUBLIC_SEARCH_PAGE_TITLE: 'public_search_page_title',
  SEARCH_ARTICLES_PLACEHOLDER: 'search_articles_placeholder',
  SEARCH_BUTTON: 'search_button',
  NO_SEARCH_RESULTS: 'no_search_results',
  SEARCH_RESULTS_FOR_LABEL: 'search_results_for_label',
  VIEW_ARTICLE_BUTTON: 'view_article_button',
  ADMIN_SEARCH_SETTINGS_TITLE: 'admin_search_settings_title', 
  REINDEX_SEARCH_BUTTON: 'reindex_search_button', 
  SHARE_ARTICLE_BUTTON: 'share_article_button', 
  GENERATE_ISSUE_PDF_BUTTON: 'generate_issue_pdf_button',
  ISSUE_PDF_GENERATION_IN_PROGRESS: 'issue_pdf_generation_in_progress',
  ISSUE_PDF_GENERATED_SUCCESS: 'issue_pdf_generated_success',
  VIEW_GENERATED_PDF_BUTTON: 'view_generated_pdf_button',
  CONFIRM_ISSUE_PDF_BUTTON: 'confirm_issue_pdf_button', 
  DIGITALLY_SIGN_SUBMISSION_CHECKBOX: 'digitally_sign_submission_checkbox',
  DIGITAL_SIGNATURE_STATUS_LABEL: 'digital_signature_status_label',
  SIGNATURE_STATUS_PENDING: 'signature_status_pending',
  SIGNATURE_STATUS_SIGNED: 'signature_status_signed',
  SIGNATURE_STATUS_ERROR: 'signature_status_error',
  SIGNATURE_STATUS_VERIFIED: 'signature_status_verified',
  VERIFY_SIGNATURE_BUTTON: 'verify_signature_button', 
  SIGNATURE_VERIFICATION_INITIATED: 'signature_verification_initiated',
  MY_ACHIEVEMENTS_TITLE: 'my_achievements_title',
  AUTHOR_LEVEL_LABEL: 'author_level_label',
  AUTHOR_LEVEL_NEW: 'author_level_new',
  AUTHOR_LEVEL_ACTIVE: 'author_level_active',
  AUTHOR_LEVEL_PRESTIGIOUS: 'author_level_prestigious',
  BADGES_LABEL: 'badges_label',
  BADGE_FIRST_ARTICLE_NAME: 'badge_first_article_name',
  BADGE_FAST_EDIT_NAME: 'badge_fast_edit_name', 
  BADGE_INTERNATIONAL_AUTHOR_NAME: 'badge_international_author_name', 
  BADGE_TOP_REVIEWER_NAME: 'badge_top_reviewer_name', 
  BADGE_MULTILINGUAL_MASTER_NAME: 'badge_multilingual_master_name',
  BADGE_CONSISTENT_CONTRIBUTOR_NAME: 'badge_consistent_contributor_name',
  BADGE_PEER_REVIEW_PRO_NAME: 'badge_peer_review_pro_name',
  EDITORIAL_STATS_TITLE: 'editorial_stats_title',
  ARTICLES_REVIEWED_LABEL: 'articles_reviewed_label',
  AVG_REVIEW_TIME_LABEL: 'avg_review_time_label',
  VIEW_RANKINGS_BUTTON: 'view_rankings_button', 
  PUBLIC_RANKINGS_PAGE_TITLE: 'public_rankings_page_title',
  RANKINGS_TOP_AUTHORS_TITLE: 'rankings_top_authors_title',
  RANKINGS_TOP_EDITORS_TITLE: 'rankings_top_editors_title',
  RANKINGS_TOP_JOURNALS_TITLE: 'rankings_top_journals_title',
  RANK_LABEL: 'rank_label',
  SCORE_LABEL: 'score_label',
  NO_RANKING_DATA: 'no_ranking_data',
  CALENDAR_PAGE_TITLE: 'calendar_page_title',
  ADD_NEW_TASK_BUTTON: 'add_new_task_button',
  TASK_LIST_TITLE: 'task_list_title',
  NO_TASKS_MESSAGE: 'no_tasks_message',
  TASK_MODAL_TITLE_ADD: 'task_modal_title_add',
  TASK_MODAL_TITLE_EDIT: 'task_modal_title_edit',
  TASK_DESCRIPTION_LABEL: 'task_description_label',
  DUE_DATE_LABEL: 'due_date_label',
  RELATED_ARTICLE_LABEL: 'related_article_label',
  MARK_AS_COMPLETE_BUTTON: 'mark_as_complete_button',
  MARK_AS_INCOMPLETE_BUTTON: 'mark_as_incomplete_button',
  SAVE_TASK_BUTTON: 'save_task_button',
  CALENDAR_EVENTS_TITLE: 'calendar_events_title',
  ARTICLE_DEADLINE_EVENT: 'article_deadline_event',
  SYSTEM_REMINDER_EVENT: 'system_reminder_event',
  TASK_COMPLETED_SUCCESS: 'task_completed_success',
  TASK_INCOMPLETE_SUCCESS: 'task_incomplete_success',
  TASK_SAVED_SUCCESS: 'task_saved_success',
  TASK_DELETED_SUCCESS: 'task_deleted_success',
  CONFIRM_DELETE_TASK_PROMPT: 'confirm_delete_task_prompt',
  NAV_CALENDAR: 'nav_calendar',
  MONTH_PREVIOUS: 'month_previous',
  MONTH_NEXT: 'month_next',
  DELETE_TASK_BUTTON: 'delete_task_button',
  EDITOR_FILTER_BY_JOURNAL_LABEL: 'editor_filter_by_journal_label',
  EDITOR_FILTER_BY_AUTHOR_NAME_LABEL: 'editor_filter_by_author_name_label',
  EDITOR_FILTER_BY_SUBMISSION_DATE_RANGE_LABEL: 'editor_filter_by_submission_date_range_label',
  EDITOR_FILTER_BY_MIN_PLAGIARISM_LABEL: 'editor_filter_by_min_plagiarism_label',
  EDITOR_SORT_BY_LABEL: 'editor_sort_by_label',
  EDITOR_SORT_SUBMISSION_DATE_NEWEST: 'editor_sort_submission_date_newest',
  EDITOR_SORT_SUBMISSION_DATE_OLDEST: 'editor_sort_submission_date_oldest',
  EDITOR_SORT_TITLE_ASC: 'editor_sort_title_asc',
  EDITOR_SORT_TITLE_DESC: 'editor_sort_title_desc',
  EDITOR_SORT_LAST_UPDATE_NEWEST: 'editor_sort_last_update_newest',
  EDITOR_SORT_LAST_UPDATE_OLDEST: 'editor_sort_last_update_oldest',
  ALL_MY_JOURNALS: 'all_my_journals',
  MIN_PLAGIARISM_PLACEHOLDER: 'min_plagiarism_placeholder',
  AI_SUGGESTIONS_MODAL_TITLE: 'ai_suggestions_modal_title',
  GRAMMAR_ISSUES_SUGGESTIONS_LABEL: 'grammar_issues_suggestions_label',
  STYLE_SUGGESTIONS_LABEL: 'style_suggestions_label',
  NO_GRAMMAR_ISSUES_FOUND: 'no_grammar_issues_found',
  NO_STYLE_SUGGESTIONS_FOUND: 'no_style_suggestions_found',
  AI_CHECK_NOT_PERFORMED_OR_UNAVAILABLE: 'ai_check_not_performed_or_unavailable',
  AI_CHECK_STATUS_PASSED: 'ai_check_status_passed',
  AI_CHECK_STATUS_PASSED_WITH_SUGGESTIONS: 'ai_check_status_passed_with_suggestions',
  AI_CHECK_STATUS_ISSUES_FOUND: 'ai_check_status_issues_found',
  AI_CHECK_STATUS_ERROR: 'ai_check_status_error',
  SUGGEST_TITLE_AI_BUTTON: 'suggest_title_ai_button',
  SUGGEST_KEYWORDS_AI_BUTTON: 'suggest_keywords_ai_button',
  SUGGEST_JOURNALS_AI_BUTTON: 'suggest_journals_ai_button',
  USE_SUGGESTED_TITLE_BUTTON: 'use_suggested_title_button',
  ADD_SUGGESTED_KEYWORD_BUTTON: 'add_suggested_keyword_button',
  SELECT_SUGGESTED_JOURNAL_BUTTON: 'select_suggested_journal_button',
  AI_ERROR_NO_SUGGESTIONS: 'ai_error_no_suggestions',
  AI_FETCHING_SUGGESTIONS: 'ai_fetching_suggestions',
  AI_SUGGESTING_KEYWORDS: 'ai_suggesting_keywords',
  PLAGIARISM_SERVICE_CONFIGURATION_TITLE: 'plagiarism_service_configuration_title',
  PLAGIARISM_CHECK_DETAILS_CARD_TITLE: 'plagiarism_check_details_card_title',
  PLAGIARISM_SERVICE_URL_LABEL: 'plagiarism_service_url_label',
  PLAGIARISM_MONTHLY_LIMIT_LABEL: 'plagiarism_monthly_limit_label',
  PLAGIARISM_ADVANCED_SETTINGS_LINK_LABEL: 'plagiarism_advanced_settings_link_label',
  RERUN_PLAGIARISM_CHECK_BUTTON: 'rerun_plagiarism_check_button',
  PLAGIARISM_CHECK_SUCCESS_RERUN: 'plagiarism_check_rerun_success',
  NAV_AI_DOCUMENT_UTILITIES: 'nav_ai_document_utilities',
  AI_DOCUMENT_UTILITIES_PAGE_TITLE: 'ai_document_utilities_page_title',
  LITERACY_CHECK_SECTION_TITLE: 'literacy_check_section_title',
  TRANSLITERATION_SECTION_TITLE: 'transliteration_section_title',
  UPLOAD_PDF_FOR_ANALYSIS_LABEL: 'upload_pdf_for_analysis_label',
  UPLOAD_PDF_FOR_TRANSLITERATION_LABEL: 'upload_pdf_for_transliteration_label',
  ANALYZE_DOCUMENT_BUTTON: 'analyze_document_button',
  TRANSLITERATE_DOCUMENT_BUTTON: 'transliterate_document_button',
  SELECT_TRANSLITERATION_DIRECTION_LABEL: 'select_transliteration_direction_label',
  CYRILLIC_TO_LATIN: 'cyrillic_to_latin',
  LATIN_TO_CYRILLIC: 'latin_to_cyrillic',
  LITERACY_REPORT_TITLE: 'literacy_report_title',
  LITERACY_SUGGESTIONS_TITLE: 'literacy_suggestions_title',
  TRANSLITERATED_TEXT_TITLE: 'transliterated_text_title',
  PROCESSING_LITERACY_CHECK: 'processing_literacy_check',
  PROCESSING_TRANSLITERATION: 'processing_transliteration',
  ERROR_PROCESSING_PDF: 'error_processing_pdf',
  ERROR_NO_FILE_SELECTED: 'error_no_file_selected',
  COPY_TEXT_BUTTON: 'copy_text_button',
  DOWNLOAD_TEXT_BUTTON: 'download_text_button',
  PDF_ANALYSIS_DESCRIPTION: 'pdf_analysis_description',
  TRANSLITERATION_DESCRIPTION: 'transliteration_description',
  PDF_TEXT_EXTRACTION_SIMULATION_NOTE: 'pdf_text_extraction_simulation_note',
  TEXT_COPIED_SUCCESS: 'text_copied_success',
  TEXT_DOWNLOAD_STARTED: 'text_download_started',
  FOOTER_CDC_CREDIT: 'footer_cdc_credit',
  FOOTER_CRADEV_CREDIT: 'footer_cradev_credit',
  NAV_PLAGIARISM_CHECKER: 'nav_plagiarism_checker',
  PLAGIARISM_CHECKER_PAGE_TITLE: 'plagiarism_checker_page_title',
  UPLOAD_DOCUMENT_FOR_PLAGIARISM_CHECK_LABEL: 'upload_document_for_plagiarism_check_label',
  RUN_PLAGIARISM_CHECK_BUTTON_GENERIC: 'run_plagiarism_check_button_generic',
  PLAGIARISM_RESULT_SECTION_TITLE: 'plagiarism_result_section_title',
  SIMILARITY_PERCENTAGE_DISPLAY: 'similarity_percentage_display',
  CERTIFICATE_ELIGIBLE_MESSAGE: 'certificate_eligible_message',
  CERTIFICATE_NOT_ELIGIBLE_MESSAGE: 'certificate_not_eligible_message',
  DOWNLOAD_PLAGIARISM_CERTIFICATE_BUTTON: 'download_plagiarism_certificate_button',
  CERTIFICATE_DOWNLOAD_PROMPT: 'certificate_download_prompt',
  ERROR_NO_FILE_FOR_PLAGIARISM_CHECK: 'error_no_file_for_plagiarism_check',
  ERROR_DURING_PLAGIARISM_CHECK: 'error_during_plagiarism_check',
  CHECKING_PLAGIARISM_MESSAGE: 'checking_plagiarism_message',
  PLAGIARISM_CHECK_THRESHOLD_NOTE: 'plagiarism_check_threshold_note',
  AI_CONTENT_PROBABILITY_LABEL: 'ai_content_probability_label',
  AI_CONTENT_ANALYSIS_SECTION_TITLE: 'ai_content_analysis_section_title',
  VIEW_AI_ANALYSIS_REPORT_BUTTON: 'view_ai_analysis_report_button',
  AI_ANALYSIS_REPORT_MODAL_TITLE: 'ai_analysis_report_modal_title',
  AI_ANALYSIS_REPORT_INTRO_LABEL: 'ai_analysis_report_intro_label',
  AI_ANALYSIS_SECTION_LABEL: 'ai_analysis_section_label',
  AI_ANALYSIS_ASSESSMENT_LABEL: 'ai_analysis_assessment_label',
  AI_ANALYSIS_EVIDENCE_LABEL: 'ai_analysis_evidence_label',
  CERTIFICATE_NOT_ELIGIBLE_AI_CONTENT: 'certificate_not_eligible_ai_content',
  PLAGIARISM_AND_AI_CHECKER_PAGE_TITLE: 'plagiarism_and_ai_checker_page_title',
  PAYMENT_CONFIRMATION_TITLE: 'payment_confirmation_title',
  PAYMENT_CONFIRMATION_MESSAGE: 'payment_confirmation_message',
  PAYMENT_AGREE_BUTTON: 'payment_agree_button',
  PAYMENT_DETAILS_TITLE: 'payment_details_title',
  PLASTIC_CARD_NUMBER_LABEL: 'plastic_card_number_label',
  MOCK_PLASTIC_CARD_NUMBER: 'mock_plastic_card_number', // Key for translation of label, not value
  UPLOAD_RECEIPT_LABEL: 'upload_receipt_label',
  SEND_BUTTON: 'send_button',
  PAYMENT_SUBMITTED_MESSAGE: 'payment_submitted_message',
  RECEIPT_REQUIRED_ERROR: 'receipt_required_error',
  ERROR_PAYMENT_FIRST: 'error_payment_first',
  NOTIFICATION_BELL_ARIA_LABEL: 'notification_bell_aria_label',
  NOTIFICATIONS_TITLE: 'notifications_title',
  NO_NOTIFICATIONS: 'no_notifications',
  NOTIFICATION_PLAGIARISM_RESULTS_READY: 'notification_plagiarism_results_ready',
  NOTIFICATION_ARTICLE_SUBMISSION_PAYMENT_APPROVED: 'notification_article_submission_payment_approved',
  MARK_AS_READ: 'mark_as_read',
  MARK_ALL_AS_READ: 'mark_all_as_read',
  CHECK_HISTORY_TITLE: 'check_history_title',
  HISTORY_DATE_COLUMN: 'history_date_column',
  HISTORY_FILENAME_COLUMN: 'history_filename_column',
  HISTORY_SIMILARITY_COLUMN: 'history_similarity_column',
  HISTORY_AI_CONTENT_COLUMN: 'history_ai_content_column',
  HISTORY_STATUS_COLUMN: 'history_status_column',
  HISTORY_NO_CHECKS_YET: 'history_no_checks_yet',
  HISTORY_STATUS_PAYMENT_PENDING_USER_ACTION: 'history_status_payment_pending_user_action',
  HISTORY_STATUS_PAYMENT_CONFIRMATION_PENDING: 'history_status_payment_confirmation_pending',
  HISTORY_STATUS_PAYMENT_DETAILS_PENDING: 'history_status_payment_details_pending',
  HISTORY_STATUS_PAYMENT_PENDING_ADMIN_APPROVAL: 'history_status_payment_pending_admin_approval',
  HISTORY_STATUS_PAYMENT_APPROVED_PROCESSING: 'history_status_payment_approved_processing',
  HISTORY_STATUS_RESULTS_READY: 'history_status_results_ready',
  CANCEL_BUTTON: 'cancel_button',
  ARTICLE_SUBMISSION_PAYMENT_CONFIRMATION_TITLE: 'article_submission_payment_confirmation_title',
  ARTICLE_SUBMISSION_PAYMENT_CONFIRMATION_MESSAGE: 'article_submission_payment_confirmation_message',
  ARTICLE_SUBMISSION_PAYMENT_DETAILS_TITLE: 'article_submission_payment_details_title',
  ARTICLE_SUBMISSION_PAYMENT_SUBMITTED_MESSAGE: 'article_submission_payment_submitted_message',
  ARTICLE_SUBMITTED_SUCCESS_AFTER_PAYMENT: 'article_submitted_success_after_payment',
  ROLE_ACCOUNTANT: 'role_accountant',
  NAV_FINANCIAL_OVERVIEW: 'nav_financial_overview',
  FINANCIAL_OVERVIEW_TITLE: 'financial_overview_title',
  TOTAL_REVENUE: 'total_revenue',
  PAID_SUBMISSIONS_COUNT: 'paid_submissions_count',
  AVERAGE_REVENUE_PER_SUBMISSION: 'average_revenue_per_submission',
  TRANSACTION_HISTORY: 'transaction_history',
  TRANSACTION_ID: 'transaction_id',
  PAYMENT_DATE: 'payment_date',
  AMOUNT: 'amount',
  PAYMENT_FOR_ARTICLE: 'payment_for_article',
  NO_TRANSACTIONS_FOUND: 'no_transactions_found',
  XIZMATLAR: 'xizmatlar',
  BOSMA_NASHRLAR: 'bosma_nashrlar',
  QORALAMALARNI_BOSHQARISH: 'qoralamalarni_boshqarish',
  CLIENT_ROLE: 'client_role',
  WRITER_ROLE: 'writer_role',
  XIZMATLARNI_BOSHQARISH: 'xizmatlarni_boshqarish'
};

// Bu NAV_LINKS objecti yangilangan
export const NAV_LINKS = {
  [UserRole.CLIENT]: [
    { path: '/dashboard', labelKey: 'boshqaruv_paneli' },
    { path: '/journals', labelKey: 'jurnallar' }, // Changed from 'maqola_yuborish'
    { path: '/my-articles', labelKey: 'mening_maqolalarim' },
    { path: '/services', labelKey: 'xizmatlar' },
    { path: '/profile', labelKey: 'profil_sahifasi' },
  ],
  [UserRole.WRITER]: [
    { path: '/writer/dashboard', labelKey: 'boshqaruv_paneli' },
    { path: '/writer/submit-article', labelKey: 'maqola_yuborish' },
    { path: '/writer/my-articles', labelKey: 'mening_maqolalarim' },
    { path: '/writer/article-drafts', labelKey: 'qoralamalarni_boshqarish' },
    { path: '/writer/printed-publications', labelKey: 'bosma_nashrlar' },
    { path: '/writer/profile', labelKey: 'profil_sahifasi' },
  ],
  [UserRole.JOURNAL_MANAGER]: [
    { path: '/dashboard', labelKey: 'boshqaruv_paneli' },
    { path: '/assigned-articles', labelKey: 'mening_maqolalarim_muharrir' },
    { path: '/journal-management', labelKey: 'mening_jurnalim' },
    { path: '/profile', labelKey: 'profil_sahifasi' },
  ],
  [UserRole.ACCOUNTANT]: [
    { path: '/dashboard', labelKey: 'boshqaruv_paneli' },
    { path: '/financial-report', labelKey: 'Moliyaviy hisobot' },
    { path: '/profile', labelKey: 'profil_sahifasi' },
  ],
  [UserRole.ADMIN]: [
    { path: '/dashboard', labelKey: 'boshqaruv_paneli' },
    { path: '/user-management', labelKey: 'foydalanuvchilarni_boshqarish' },
    { path: '/journal-management', labelKey: 'jurnallarni_boshqarish_admin' },
    { path: '/article-overview', labelKey: 'maqolalarni_boshqarish_admin' },
    { path: '/applications-overview', labelKey: 'Tahririyat arizalari' },
    { path: '/financial-report', labelKey: 'Moliyaviy hisobot' },
    { path: '/audit-log', labelKey: 'audit_jurnali_admin' },
    { path: '/system-settings', labelKey: 'tizim_sozlamalari' },
    { path: '/service-management', labelKey: 'xizmatlarni_boshqarish' },
    { path: '/admin/printed-publications', labelKey: 'bosma_nashrlar' },
    { path: '/soha-management', labelKey: 'soha_maydonlari_boshqaruvi' },
    { path: '/document-type-management', labelKey: 'hujjat_turlari_boshqaruvi' },
  ]
};

export const API_KEY_ERROR_MESSAGE = "API_KEY muhit o'zgaruvchisi o'rnatilmagan. Iltimos, uni sozlang.";