
import { Language, LocalizedText } from '../types';
import { LocalizationKeys, MOCK_PLAGIARISM_CHECK_PRICE, MOCK_ARTICLE_SUBMISSION_PRICE, PLAGIARISM_CERTIFICATE_THRESHOLD, AI_CONTENT_CERTIFICATE_THRESHOLD } from '../constants'; 

interface Translations {
  [Language.UZ]: LocalizedText;
}

export const translations: Translations = {
  [Language.UZ]: {
    maqola_muvaffaqiyatli_yuborildi: 'Maqola koʻrib chiqish uchun muvaffaqiyatli yuborildi!',
    jurnallar: 'Jurnallar',
    [LocalizationKeys.APP_TITLE_FULL]: 'Phoenix Ilmiy Nashriyot Markazi',
    [LocalizationKeys.APP_TITLE_SHORT]: 'PINM',
    all_rights_reserved: 'Barcha huquqlar himoyalangan.',
    login_button: 'Kirish',
    logout_button: 'Chiqish',
    register_button: 'Roʻyxatdan oʻtish',
    login_welcome_message: 'Xush kelibsiz! Iltimos, telefon raqamingiz bilan tizimga kiring.',
    register_welcome_message: 'PINMga qoʻshiling va ilmiy ishlaringizni nashr eting va boshqaring.',
    phone_label: 'Telefon raqam',
    password_label: 'Parol',
    role_label: 'Rol',
    name_label: 'Ism',
    surname_label: 'Familiya',
    confirm_password_label: 'Parolni tasdiqlang',
    password_placeholder_min_chars: 'Kamida 6 belgi',
    confirm_password_placeholder: 'Parolni qayta kiriting',
    role_client: 'Muallif',
    role_journal_manager: 'Redaktor',
    [LocalizationKeys.ROLE_ACCOUNTANT]: 'Bug\'alter',
    role_admin: 'Administrator',
    login_failed_default_error: 'Kirish muvaffaqiyatsiz tugadi. Iltimos, ma’lumotlaringizni tekshiring.',
    registration_failed_default_error: 'Roʻyxatdan oʻtish muvaffaqiyatsiz tugadi. Iltimos, qaytadan urinib koʻring.',
    password_mismatch_error: 'Parollar mos kelmadi.',
    password_too_short_error: 'Parol kamida 6 belgidan iborat boʻlishi kerak.',
    dont_have_account_prompt: "Hisobingiz yoʻqmi?",
    register_link: 'Bu yerda roʻyxatdan oʻting',
    already_have_account_prompt: 'Hisobingiz bormi?',
    login_link: 'Bu yerda kiring',
    create_account_title: 'Hisob Yaratish',
    register_as_label: 'Sifatida roʻyxatdan oʻtish',
    dashboard: 'Boshqaruv Paneli',
    submit_article: 'Maqola Yuborish',
    my_articles: 'Mening Maqolalarim',
    profile: 'Profil',
    assigned_articles: 'Menga Biriktirilgan Maqolalar',
    user_management: 'Foydalanuvchilarni Boshqarish',
    journal_management: 'Jurnallarni Boshqarish',
    system_settings: 'Tizim Sozlamalari',
    select_language: 'Tilni tanlang',
    boshqaruv_paneli: 'Boshqaruv Paneli',
    maqola_yuborish: 'Maqola Yuborish',
    mening_maqolalarim: 'Mening Maqolalarim',
    profil_sahifasi: 'Profil Sahifasi',
    mening_maqolalarim_muharrir: 'Biriktirilgan Maqolalar',
    [LocalizationKeys.MENING_JURNALIM]: 'Mening Jurnalim',
    foydalanuvchilarni_boshqarish: 'Foydalanuvchilarni Boshqarish',
    [LocalizationKeys.JURNALLARNI_BOSHQARISH_ADMIN]: 'Jurnallarni Boshqarish (Admin)',
    tizim_sozlamalari: 'Tizim Sozlamalari',
    soha_maydonlari_boshqaruvi: 'SOHA Maydonlari Boshqaruvi',
    hujjat_turlari_boshqaruvi: 'Hujjat Turlari Boshqaruvi',
    welcome_back: 'Xush kelibsiz',
    dashboard_subtitle: 'Bu yerda sizning faoliyatingiz va tizim holati haqida umumiy ma’lumot.',
    my_articles_summary: 'Maqolalarim Xulosasi',
    articles_pending_review: 'Koʻrib Chiqilmoqda:',
    articles_need_revision: 'Tahrirlash Kerak:',
    articles_accepted: 'Qabul Qilingan:',
    submit_new_article_button: 'Yangi Maqola Yuborish',
    recent_activity: 'Soʻnggi Faoliyat',
    activity_article_accepted: '"Sog\'liqni saqlashda SI" maqolasi qabul qilindi.',
    activity_comment_received: '"Kvant hisoblashlari" boʻyicha yangi izoh keldi.',
    quick_links: 'Tezkor Havolalar',
    view_all_my_articles: 'Barcha Maqolalarimni Koʻrish',
    manage_my_profile: 'Profilimni Boshqarish',
    articles_for_review: 'Koʻrib Chiqish Uchun Maqolalar',
    new_submissions: 'Yangi Kelganlar:',
    currently_reviewing: 'Hozir Koʻrib Chiqilmoqda:',
    view_assigned_articles_button: 'Biriktirilgan Maqolalarni Koʻrish',
    journal_overview: 'Jurnal Umumiy Koʻrinishi: Kvant Fizikasi Jurnali',
    total_articles_in_journal: 'Jurnaldagi Umumiy Maqolalar:',
    average_review_time: 'Oʻrtacha Koʻrib Chiqish Vaqti:',
    quick_actions_editor: 'Tezkor Amallar',
    view_journal_statistics: 'Jurnal Statistikasini Koʻrish',
    system_overview: 'Tizim Umumiy Koʻrinishi',
    total_users: 'Umumiy Foydalanuvchilar:',
    total_journals: 'Umumiy Jurnallar:',
    total_articles_system: 'Tizimdagi Umumiy Maqolalar:',
    view_system_statistics: 'Tizim Statistikasini Koʻrish',
    management_tools: 'Boshqaruv Vositalari',
    manage_users_button: 'Foydalanuvchilarni Boshqarish',
    manage_journals_button: 'Jurnallarni Boshqarish',
    system_health: 'Tizim Holati',
    ai_service_status: 'SI Xizmati Holati:',
    plagiarism_service_status: 'Plagiat Xizmati:',
    operational: 'Ishlamoqda',
    degraded: 'Sekinlashgan',
    down: 'Ishlamayapti',
    unconfigured: 'Sozlanmagan',
    go_to_system_settings: 'Tizim Sozlamalariga Oʻtish',
    loading_user_data: 'Foydalanuvchi ma’lumotlari yuklanmoqda...',
    submit_new_article_title: 'Yangi Maqola Yuborish',
    article_details_title: 'Maqola Tafsilotlari',
    select_journal_label: 'Jurnalni Tanlang',
    article_title_label: 'Maqola Sarlavhasi',
    article_title_placeholder: 'Maqola sarlavhasini kiriting',
    article_abstract_label: 'Annotatsiya',
    article_abstract_placeholder: 'Maqolangizning qisqacha mazmunini kiriting',
    keywords_label: 'Kalit Soʻzlar (vergul bilan ajrating)',
    keywords_placeholder: 'Masalan, SI, Mashinali oʻqitish, Ilmiy nashr',
    upload_article_file_title: 'Maqola Faylini Yuklash',
    article_file_label_docx: 'Maqola Fayli (.doc, .docx)',
    article_file_label_docx_pdf: 'Maqola Fayli (.doc, .docx, .pdf)',
    selected_file_label: 'Tanlangan fayl:',
    submit_article_button: 'Maqolani Yuborish',
    all_fields_required_error: 'Sarlavha, annotatsiya, kalit so‘zlar va maqola fayli talab qilinadi.',
    file_type_error_docx: 'Iltimos, .doc yoki .docx faylini yuklang.',
    file_type_error_docx_pdf: 'Iltimos, .doc, .docx yoki .pdf faylini yuklang.',
    article_submitted_success: 'Maqola muvaffaqiyatli yuborildi! Holatini "Mening Maqolalarim" boʻlimida kuzatishingiz mumkin.',
    coauthors_section_title: 'Hammualliflar (Ixtiyoriy)',
    coauthor_name_label: 'Hammuallif Ismi',
    coauthor_phone_label: 'Hammuallif Telefon Raqami',
    name_placeholder: 'Ismni kiriting',
    add_coauthor_button: 'Hammuallif Qoʻshish',
    remove_button: 'Oʻchirish',
    ai_keyword_suggestion_title: 'SI Kalit Soʻz Taklifi',
    ai_keyword_suggestion_desc: 'Maqolangiz sarlavhasi va annotatsiyasini kiriting, SI tegishli kalit soʻzlarni taklif qiladi.',
    suggest_keywords_button: 'Kalit Soʻzlarni Taklif Qilish',
    suggested_keywords_label: 'Taklif Qilingan Kalit Soʻzlar:',
    ai_error_title_abstract_required: 'SI funksiyalari uchun sarlavha, annotatsiya va kalit soʻzlarni kiriting.',
    ai_error_no_keywords: 'SI kalit soʻzlarni taklif qila olmadi. Javob boʻsh.',
    ai_error_fetching: 'SI kalit soʻzlarini olishda xatolik:',
    ai_processing_message: 'SI oʻylanmoqda...',
    my_articles_title: 'Mening Maqolalarim',
    status_pending: 'Kutilmoqda',
    status_reviewing: 'Koʻrib Chiqilmoqda',
    status_needs_revision: 'Tahrirlash Kerak',
    status_accepted: 'Qabul Qilindi',
    status_rejected: 'Rad Etildi',
    [LocalizationKeys.STATUS_PUBLISHED]: 'Nashr Etildi',
    journal_label: 'Jurnal:',
    submitted_on_label: 'Yuborilgan Sana:',
    view_details_button: 'Tafsilotlarni Koʻrish',
    resubmit_button: 'Qayta Yuborish',
    download_final_version_button: 'Yakuniy Versiyani Yuklab Olish',
    loading_my_articles: 'Maqolalaringiz yuklanmoqda...',
    no_articles_submitted: 'Siz hali hech qanday maqola yubormagansiz.',
    submit_your_first_article: 'Birinchi Maqolangizni Yuboring',
    view_details_for_article: '{id} maqolasi uchun tafsilotlarni koʻrish (Amalga oshirilmagan)',
    resubmit_article_prompt: '{id} maqolasini qayta yuborish (Amalga oshirilmagan)',
    download_final_version_prompt: 'Yakuniy versiyani yuklab olish (Amalga oshirilmagan)',
    user_profile_title: 'Foydalanuvchi Profili',
    personal_information_title: 'Shaxsiy Ma’lumotlar',
    save_changes_button: 'Oʻzgarishlarni Saqlash',
    edit_profile_button: 'Profilni Tahrirlash',
    cancel_button: 'Bekor Qilish',
    change_password_title: 'Parolni Oʻzgartirish',
    current_password_label: 'Joriy Parol',
    new_password_label: 'Yangi Parol',
    confirm_new_password_label: 'Yangi Parolni Tasdiqlang',
    update_password_button: 'Parolni Yangilash',
    profile_updated_success: 'Profil muvaffaqiyatli yangilandi!',
    password_changed_success: 'Parol muvaffaqiyatli oʻzgartirildi!',
    loading_profile: 'Profil yuklanmoqda...',
    notfound_title: 'Sahifa Topilmadi',
    notfound_message: 'Voy! Siz qidirayotgan sahifa mavjud emas. U koʻchirilgan yoki oʻchirilgan boʻlishi mumkin.',
    go_to_dashboard_button: 'Boshqaruv Paneliga Oʻtish',
    user_management_title: 'Foydalanuvchilarni Boshqarish',
    add_new_user_button: 'Yangi Foydalanuvchi Qoʻshish',
    search_users_label: 'Foydalanuvchilarni Qidirish (Ism, Familiya, Telefon)',
    type_to_search_placeholder: 'Qidirish uchun yozing...',
    actions_label: 'Amallar',
    edit_user_button: 'Tahrirlash',
    delete_user_button: 'Oʻchirish',
    loading_users: 'Foydalanuvchilar yuklanmoqda...',
    no_users_found_criteria: 'Sizning mezonlaringizga mos keladigan foydalanuvchilar topilmadi.',
    edit_user_modal_title: 'Foydalanuvchini Tahrirlash',
    add_new_user_modal_title: 'Yangi Foydalanuvchi Qoʻshish',
    all_required_fields_error_user: 'Ism, familiya, telefon raqami va rol talab qilinadi.',
    create_user_button: 'Foydalanuvchi Yaratish',
    set_initial_password_placeholder: 'Boshlangʻich parolni oʻrnating (kamida 6 belgi)',
    confirm_delete_user_prompt: 'Haqiqatan ham bu foydalanuvchini oʻchirmoqchimisiz? Bu amalni qaytarib boʻlmaydi.',
    user_updated_successfully: 'Foydalanuvchi muvaffaqiyatli yangilandi.',
    user_created_successfully: 'Foydalanuvchi muvaffaqiyatli yaratildi.',
    user_deleted_successfully: 'Foydalanuvchi muvaffaqiyatli oʻchirildi.',
    select_all_users_label: 'Barcha foydalanuvchilarni tanlash',
    select_user_label: 'Foydalanuvchini tanlash',
    users_selected_count: 'foydalanuvchi tanlandi',
    journal_management_title: 'Jurnallarni Boshqarish',
    add_new_journal_button: 'Yangi Jurnal Qoʻshish',
    search_journals_label: 'Jurnallarni Qidirish (Nomi, Tavsifi)',
    manager_label: 'Menejer:',
    rules_file_label: 'Qoidalar:',
    template_file_label: 'Shablon:',
    delete_journal_button: 'Jurnalni Oʻchirish',
    loading_journals: 'Jurnallar yuklanmoqda...',
    no_journals_found_criteria: 'Sizning mezonlaringizga mos keladigan jurnallar topilmadi.',
    edit_journal_modal_title: 'Jurnalni Tahrirlash',
    add_new_journal_modal_title: 'Yangi Jurnal Qoʻshish',
    journal_name_label: 'Jurnal Nomi',
    journal_description_label: 'Tavsif',
    assign_manager_label: 'Menejer Tayinlash (Redaktor)',
    select_editor_option: '-- Redaktorni Tanlang --',
    rules_file_pdf_doc_label: 'Qoidalar Fayli (PDF/DOCX)',
    template_file_doc_label: 'Shablon Fayli (DOCX)',
    current_file_label: 'Joriy:',
    create_journal_button: 'Jurnal Yaratish',
    name_desc_manager_required_error: 'Jurnal nomi, tavsifi va menejeri talab qilinadi.',
    confirm_delete_journal_prompt: 'Haqiqatan ham bu jurnalni oʻchirmoqchimisiz? Bu bogʻliq maqolalarga ta’sir qilishi mumkin.',
    unassigned: 'Tayinlanmagan',
    journal_updated_successfully: 'Jurnal muvaffaqiyatli yangilandi.',
    journal_created_successfully: 'Jurnal muvaffaqiyatli yaratildi.',
    journal_deleted_successfully: 'Jurnal muvaffaqiyatli oʻchirildi.',
    template_name_required: 'Shablon nomi talab qilinadi.',
    select_template_to_load: '-- Yuklash uchun Shablonni Tanlang --',
    publisher_label: 'Nashriyotchi',
    publisher_name_placeholder: 'Masalan, PINM Nashriyoti',
    assigned_articles_title: 'Biriktirilgan Maqolalar',
    search_articles_label: 'Maqolalarni Qidirish (Sarlavha/Kalit Soʻzlar)',
    all_statuses: 'Barcha Holatlar',
    loading_assigned_articles: 'Biriktirilgan maqolalar yuklanmoqda...',
    review_article_button: 'Maqolani Koʻrib Chiqish',
    review_article_title: 'Maqolani Koʻrib Chiqish',
    article_content_title: 'Maqola Mazmuni',
    submitted_by_author: 'Yuborgan Muallif:',
    abstract_label: 'Annotatsiya',
    versions_and_files_title: 'Versiyalar va Fayllar',
    version_label: 'Versiya',
    no_notes_for_version: 'Ushbu versiya uchun qaydlar yoʻq.',
    download_button: 'Yuklab Olish',
    preview_in_browser_button: 'Eng Soʻnggi Versiyani Brauzerda Koʻrish',
    ai_plagiarism_checks_title: 'SI va Plagiat Tekshiruvlari',
    plagiarism_check_status: 'Plagiat Tekshiruvi:',
    completed_similarity: 'Tugallandi, {percentage}% Oʻxshashlik',
    report_not_available: 'Hisobot mavjud emas',
    plagiarism_check_not_run: 'Plagiat tekshiruvi oʻtkazilmagan yoki mavjud emas.',
    view_report_button: 'Hisobotni Koʻrish',
    ai_grammar_style_check: 'SI Grammatika va Uslub Tekshiruvi:',
    passed_with_suggestions: 'Takliflar bilan oʻtdi',
    view_suggestions_button: 'Takliflarni Koʻrish',
    actions_and_comments_title: 'Amallar va Izohlar',
    editor_comments_for_author_label: 'Muallif uchun Izohlar (ixtiyoriy)',
    enter_comments_placeholder: 'Fikr-mulohazalaringizni yoki holat oʻzgarishi sabablarini kiriting...',
    request_revision_button: 'Tahrirlashni Soʻrash',
    reject_article_button: 'Maqolani Rad Etish',
    accept_article_title_section: 'Maqolani Qabul Qilish',
    upload_final_edited_version_label: 'Yakuniy Tahrirlangan Versiyani Yuklash (PDF/DOCX)',
    accept_and_publish_button: 'Maqolani Qabul Qilish',
    communication_with_author_title: 'Muallif Bilan Aloqa',
    chat_module_placeholder: 'Muallif bilan ilova ichidagi suhbat shu yerda paydo boʻladi.',
    loading_article_details: 'Maqola tafsilotlari yuklanmoqda...',
    article_not_found: 'Maqola topilmadi.',
    status_updated_successfully_to: 'Holat {status} ga muvaffaqiyatli yangilandi.',
    final_version_required_for_acceptance: 'Maqolani Qabul Qilingan deb belgilash uchun uning yakuniy tahrirlangan versiyasini yuklang.',
    file_type_error_pdf_docx: 'Iltimos, PDF yoki DOCX faylini yuklang.',
    download_file_prompt: '{filePath} faylini yuklab olish (Amalga oshirilmagan)',
    preview_in_browser_prompt: 'Brauzerda koʻrish (Amalga oshirilmagan)',
    API_KEY_ERROR_MESSAGE: "API_KEY muhit o'zgaruvchisi o'rnatilmagan. Iltimos, uni sozlang.",
    [LocalizationKeys.PRELIMINARY_PLAGIARISM_CHECK]: 'Dastlabki Plagiat Tekshiruvi',
    [LocalizationKeys.RUN_PLAGIARISM_CHECK_BUTTON]: 'Plagiat Tekshiruvini Oʻtkazish',
    [LocalizationKeys.PLAGIARISM_CHECK_RESULT]: 'Plagiat Tekshiruvi Natijasi',
    [LocalizationKeys.SIMILARITY_PERCENTAGE]: 'Oʻxshashlik Foizi:',
    [LocalizationKeys.VIEW_PLAGIARISM_REPORT]: 'Toʻliq Hisobotni Koʻrish',
    [LocalizationKeys.AI_JOURNAL_SUGGESTION_TITLE]: 'SI Jurnal Taklifi',
    ai_journal_suggestion_desc: "Maqolangiz mazmuniga asoslanib, SI tomonidan jurnal tavsiyalarini oling.",
    [LocalizationKeys.GET_JOURNAL_SUGGESTIONS_BUTTON]: 'Jurnal Takliflarini Olish (SI)',
    [LocalizationKeys.SUGGESTED_JOURNALS]: 'Taklif Qilingan Jurnallar:',
    [LocalizationKeys.REASONING]: 'Sabab:',
    [LocalizationKeys.AI_REFERENCE_CHECK_TITLE]: 'SI Adabiyotlar Formatini Tekshirish',
    ai_reference_check_desc: "Adabiyotlaringizning bir qismini SI tomonidan format tahlili va takliflar uchun joylashtiring.",
    [LocalizationKeys.CHECK_REFERENCES_BUTTON]: 'Adabiyotlarni Tekshirish (SI)',
    [LocalizationKeys.REFERENCE_ANALYSIS_RESULT]: 'Adabiyotlar Tahlili:',
    [LocalizationKeys.AI_ABSTRACT_HELP_TITLE]: 'SI Annotatsiya Yordami',
    [LocalizationKeys.IMPROVE_ABSTRACT_BUTTON]: 'Annotatsiyani SI Bilan Yaxshilash',
    [LocalizationKeys.GENERATE_ABSTRACT_SNIPPET_BUTTON]: 'Annotatsiya Parchasini Yaratish (SI)',
    [LocalizationKeys.AI_SUGGESTED_ABSTRACT]: 'SI Taklif Qilgan Annotatsiya:',
    [LocalizationKeys.COMPARE_VERSIONS_BUTTON]: 'Versiyalarni Solishtirish',
    [LocalizationKeys.COAUTHOR_CONTRIBUTION_SHARE_LABEL]: 'Hammuallifning Hissasi/Ulishi',
    [LocalizationKeys.COAUTHOR_CONTRIBUTION_SHARE_PLACEHOLDER]: 'Masalan, 40% yoki Konseptualizatsiya',
    [LocalizationKeys.ARTICLE_NOTES_TITLE]: 'Shaxsiy Qaydlarim',
    [LocalizationKeys.ADD_NOTE_BUTTON]: 'Qayd Qoʻshish',
    [LocalizationKeys.ARTICLE_TAGS_TITLE]: 'Maqola Teglari',
    [LocalizationKeys.ADD_TAG_BUTTON]: 'Teg Qoʻshish',
    [LocalizationKeys.NO_NOTES_YET]: 'Hali shaxsiy qaydlar qoʻshilmagan.',
    [LocalizationKeys.NO_TAGS_YET]: 'Hali teglar qoʻshilmagan.',
    [LocalizationKeys.JOURNAL_SUBMISSION_CHECKLIST_TITLE]: 'Jurnalga Yuborish Nazorat Roʻyxati',
    [LocalizationKeys.NOTIFICATION_PREFERENCES_TITLE]: 'Bildirishnoma Sozlamalari',
    [LocalizationKeys.NOTIFY_STATUS_CHANGE]: 'Maqola Holati Oʻzgarishlari (Umumiy)',
    [LocalizationKeys.NOTIFY_NEW_MESSAGE]: 'Yangi Xabarlar',
    [LocalizationKeys.NOTIFY_DEADLINE_REMINDER]: 'Yuborish Muddatlari Haqida Eslatmalar',
    [LocalizationKeys.DOWNLOAD_ACCEPTANCE_CERTIFICATE_BUTTON]: 'Qabul Qilinganlik Sertifikatini Yuklab Olish',
    [LocalizationKeys.CERTIFICATE_GENERATION_PROMPT]: 'Sertifikat yaratish/yuklab olish (Amalga oshirilmagan)',
    [LocalizationKeys.AI_ERROR_NO_JOURNAL_SUGGESTIONS]: 'SI hozirda jurnal taklif qila olmadi.',
    [LocalizationKeys.AI_ERROR_REFERENCE_ANALYSIS]: 'SI adabiyotlar tahlili paytida xatolik.',
    [LocalizationKeys.AI_ERROR_ABSTRACT_HELP]: 'SI annotatsiya yordami paytida xatolik.',
    [LocalizationKeys.VERSION_COMPARISON_UNAVAILABLE]: 'Ushbu maqola uchun versiyalarni solishtirish hali mavjud emas.',
    [LocalizationKeys.NOTES_SAVE_SUCCESS]: 'Qayd muvaffaqiyatli saqlandi.',
    [LocalizationKeys.TAGS_SAVE_SUCCESS]: 'Teg muvaffaqiyatli qoʻshildi.',
    [LocalizationKeys.CHECKLIST_NOT_AVAILABLE]: 'Ushbu jurnal uchun yuborish nazorat roʻyxati mavjud emas.',
    [LocalizationKeys.ENTER_NOTE_PLACEHOLDER]: 'Shaxsiy qaydingizni shu yerga kiriting...',
    [LocalizationKeys.ENTER_TAG_PLACEHOLDER]: 'Tegni kiriting...',
    [LocalizationKeys.PLAGIARISM_CHECK_RUNNING]: 'Plagiat tekshiruvi amalga oshirilmoqda...',
    [LocalizationKeys.AI_ANALYZING_REFERENCES]: 'SI adabiyotlarni tahlil qilmoqda...',
    [LocalizationKeys.AI_IMPROVING_ABSTRACT]: 'SI annotatsiyani yaxshilamoqda...',
    [LocalizationKeys.AI_SUGGESTING_JOURNALS]: 'SI jurnallarni taklif qilmoqda...',
    [LocalizationKeys.API_KEY_REQUIRED_FOR_AI_FEATURE]: 'Ushbu SI funksiyasidan foydalanish uchun API kaliti talab qilinadi. Iltimos, uni sozlang.',
    use_this_abstract_button: 'Ushbu Annotatsiyadan Foydalanish',
    abstract_needed_for_plagiarism_check: 'Ushbu soxta plagiat tekshiruvi uchun maqola annotatsiyasi kerak.',
    plagiarism_check_completed_successfully: 'Plagiat tekshiruvi muvaffaqiyatli yakunlandi.',
    new_note_label: 'Yangi Qayd',
    new_tag_label: 'Yangi Teg',
    notes_count_label: 'Shaxsiy Qaydlar:',
    reference_text_required_for_analysis: 'Tahlil uchun adabiyotlar matni (masalan, hujjatingizdan) kerak.',
    paste_references_label: 'Adabiyotlaringizning kichik bir qismini SI tahlili uchun shu yerga joylashtiring (ixtiyoriy):',
    references_placeholder_example: 'Masalan: Smith, J. (2022). Mening ajoyib maqolam. Tadqiqotlar Jurnali, 1(2), 123-145.',
    original_reference_label: 'Asl nusxasi:',
    issue_label: 'Masala:',
    suggestion_label: 'Taklif:',
    [LocalizationKeys.ADMIN_DASHBOARD_TITLE]: 'Administrator Boshqaruv Paneli',
    [LocalizationKeys.SYSTEM_HEALTH_TITLE]: 'Tizim Holati',
    [LocalizationKeys.DATABASE_STATUS_LABEL]: 'Ma’lumotlar Bazasi Holati',
    [LocalizationKeys.API_SERVICE_STATUS_LABEL]: 'API Xizmati Holati',
    [LocalizationKeys.STORAGE_USAGE_LABEL]: 'Xotira Foydalanish Foizi',
    [LocalizationKeys.LAST_BACKUP_LABEL]: 'Oxirgi Zaxira Nusxasi',
    [LocalizationKeys.INTEGRATION_STATUS_TITLE]: 'Integratsiya Holati',
    [LocalizationKeys.AI_GEMINI_SERVICE_LABEL]: 'SI Xizmati (Gemini)',
    [LocalizationKeys.PLAGIARISM_CHECKER_SERVICE_LABEL]: 'Plagiat Tekshirish Xizmati',
    [LocalizationKeys.DOI_PROVIDER_SERVICE_LABEL]: 'DOI Provayderi',
    [LocalizationKeys.KEY_SET_LABEL]: 'Kalit Oʻrnatilgan',
    [LocalizationKeys.KEY_NOT_SET_LABEL]: 'Kalit Oʻrnatilmagan',
    [LocalizationKeys.LAST_CHECKED_LABEL]: 'Oxirgi Tekshiruv',
    [LocalizationKeys.STUCK_ARTICLES_TITLE]: 'Qolib Ketgan Maqolalar',
    [LocalizationKeys.VIEW_STUCK_ARTICLES_BUTTON]: 'Qolib Ketgan Maqolalarni Koʻrish',
    [LocalizationKeys.NO_STUCK_ARTICLES_MESSAGE]: 'Hozirda hech qanday maqola qolib ketmaganga oʻxshaydi.',
    [LocalizationKeys.USER_MANAGEMENT_BULK_ACTIONS_LABEL]: 'Ommaviy Amallar',
    [LocalizationKeys.SELECT_ACTION_LABEL]: '-- Amalni Tanlang --',
    [LocalizationKeys.DEACTIVATE_SELECTED_ACTION]: 'Tanlanganlarni Oʻchirish',
    [LocalizationKeys.ACTIVATE_SELECTED_ACTION]: 'Tanlanganlarni Faollashtirish',
    [LocalizationKeys.ASSIGN_ROLE_SELECTED_ACTION]: 'Tanlanganlarga Rol Tayinlash',
    [LocalizationKeys.APPLY_BULK_ACTION_BUTTON]: 'Qoʻllash',
    [LocalizationKeys.SELECT_USERS_FOR_BULK_ACTION_PROMPT]: 'Iltimos, foydalanuvchilarni va amalni tanlang.',
    [LocalizationKeys.BULK_ACTION_SUCCESS_MESSAGE]: 'Ommaviy amal muvaffaqiyatli qoʻllanildi.',
    [LocalizationKeys.JOURNAL_TEMPLATE_MANAGEMENT_TITLE]: 'Jurnal Konfiguratsiya Shablonlari',
    [LocalizationKeys.SAVE_AS_TEMPLATE_BUTTON]: 'Joriyni Shablon Sifatida Saqlash',
    [LocalizationKeys.LOAD_FROM_TEMPLATE_BUTTON]: 'Shablondan Yuklash',
    [LocalizationKeys.NEW_TEMPLATE_NAME_LABEL]: 'Yangi Shablon Nomi',
    [LocalizationKeys.NEW_TEMPLATE_NAME_PLACEHOLDER]: 'Shablon nomini kiriting...',
    [LocalizationKeys.SELECT_TEMPLATE_LABEL]: 'Shablonni Tanlang',
    [LocalizationKeys.TEMPLATE_SAVED_SUCCESS_MESSAGE]: 'Jurnal shabloni muvaffaqiyatli saqlandi.',
    [LocalizationKeys.TEMPLATE_LOADED_SUCCESS_MESSAGE]: 'Jurnal sozlamalari shablondan yuklandi.',
    [LocalizationKeys.TEMPLATE_DELETED_SUCCESS_MESSAGE]: 'Jurnal shabloni muvaffaqiyatli oʻchirildi.',
    [LocalizationKeys.DELETE_TEMPLATE_BUTTON]: 'Shablonni Oʻchirish',
    [LocalizationKeys.CONFIRM_DELETE_TEMPLATE_PROMPT]: 'Haqiqatan ham bu jurnal shablonini oʻchirmoqchimisiz?',
    [LocalizationKeys.SYSTEM_SETTINGS_TITLE_ADMIN]: 'Tizim Sozlamalari',
    [LocalizationKeys.NOTIFICATION_TEMPLATE_MANAGEMENT_TITLE]: 'Bildirishnoma Shablonlarini Boshqarish',
    [LocalizationKeys.SELECT_NOTIFICATION_EVENT_LABEL]: 'Bildirishnoma Hodisasini Tanlang',
    [LocalizationKeys.SUBJECT_UZ_LABEL]: 'Mavzu (Oʻzbekcha)',
    [LocalizationKeys.BODY_UZ_LABEL]: 'Matn (Oʻzbekcha)',
    [LocalizationKeys.SAVE_NOTIFICATION_TEMPLATE_BUTTON]: 'Shablonni Saqlash',
    [LocalizationKeys.NOTIFICATION_TEMPLATE_UPDATED_SUCCESS_MESSAGE]: 'Bildirishnoma shabloni muvaffaqiyatli yangilandi.',
    [LocalizationKeys.AVAILABLE_PLACEHOLDERS_LABEL]: 'Mavjud Oʻrniga Qoʻyiladigan Soʻzlar',
    [LocalizationKeys.INTEGRATION_SETTINGS_TITLE]: 'Integratsiya Xizmatlari Konfiguratsiyasi',
    [LocalizationKeys.SERVICE_NAME_LABEL]: 'Xizmat Nomi',
    [LocalizationKeys.API_KEY_MASKED_LABEL]: 'API Kaliti (Maskalangan)',
    [LocalizationKeys.SET_API_KEY_BUTTON]: 'API Kalitini Oʻrnatish/Yangilash',
    [LocalizationKeys.SERVICE_ENABLED_LABEL]: 'Xizmat Yoqilgan',
    [LocalizationKeys.AI_MODULES_SETTINGS_TITLE]: 'SI Modullari',
    [LocalizationKeys.KEYWORD_SUGGESTION_MODULE_LABEL]: 'Kalit Soʻz Taklifi',
    [LocalizationKeys.ABSTRACT_IMPROVEMENT_MODULE_LABEL]: 'Annotatsiyani Yaxshilash',
    [LocalizationKeys.JOURNAL_SUGGESTION_MODULE_LABEL]: 'Jurnal Taklifi',
    [LocalizationKeys.REFERENCE_CHECKING_MODULE_LABEL]: 'Adabiyotlarni Tekshirish',
    [LocalizationKeys.TITLE_SUGGESTION_MODULE_LABEL]: 'Sarlavha Taklifi',
    [LocalizationKeys.JOURNAL_COMPLIANCE_CHECK_MODULE_LABEL]: 'Jurnalga Muvofiqlik Tekshiruvi',
    [LocalizationKeys.SAVE_INTEGRATION_SETTINGS_BUTTON]: 'Sozlamalarni Saqlash',
    [LocalizationKeys.INTEGRATION_SETTINGS_UPDATED_SUCCESS_MESSAGE]: 'Integratsiya sozlamalari yangilandi.',
    [LocalizationKeys.GRANULAR_ROLES_TITLE]: 'Nozik Sozlanadigan Rollar va Ruxsatlarni Boshqarish',
    [LocalizationKeys.GRANULAR_ROLES_DESC]: 'Kengaytirilgan rollar va ruxsatlar konfiguratsiyasi (Kelajakdagi Yangilanish).',
    [LocalizationKeys.AUDIT_LOG_TITLE]: 'Audit Jurnali',
    [LocalizationKeys.FILTER_BY_USER_LABEL]: 'Foydalanuvchi Boʻyicha Filtr (Telefon/ID)',
    user_phone_or_id_placeholder: 'Foydalanuvchi Telefoni yoki IDsi',
    [LocalizationKeys.FILTER_BY_ACTION_TYPE_LABEL]: 'Amal Turi Boʻyicha Filtr',
    [LocalizationKeys.FILTER_BY_STATUS_LABEL]: 'Holat Boʻyicha Filtr',
    [LocalizationKeys.FILTER_BY_DATE_RANGE_LABEL]: 'Sana Oraligʻi Boʻyicha Filtr',
    [LocalizationKeys.EXPORT_AUDIT_LOG_BUTTON]: 'Jurnalni Eksport Qilish (CSV)',
    [LocalizationKeys.AUDIT_LOG_EXPORTED_MESSAGE]: 'Audit jurnali eksporti boshlandi (soxta).',
    [LocalizationKeys.NO_AUDIT_LOGS_MESSAGE]: 'Mezonlarga mos keladigan audit yozuvlari topilmadi.',
    [LocalizationKeys.USER_ID_LABEL]: 'Foydalanuvchi',
    [LocalizationKeys.ACTION_TYPE_LABEL]: 'Amal Turi',
    [LocalizationKeys.TIMESTAMP_LABEL]: 'Vaqt Belgisi',
    [LocalizationKeys.DETAILS_LABEL]: 'Tafsilotlar',
    [LocalizationKeys.ARTICLE_OVERVIEW_TITLE_ADMIN]: 'Maqolalar Umumiy Koʻrinishi (Admin)',
    [LocalizationKeys.FILTER_BY_JOURNAL_LABEL]: 'Jurnal Boʻyicha Filtr',
    [LocalizationKeys.FILTER_BY_AUTHOR_LABEL]: 'Muallif Boʻyicha Filtr',
    [LocalizationKeys.REASSIGN_EDITOR_BUTTON]: 'Redaktorni Qayta Tayinlash',
    [LocalizationKeys.SELECT_NEW_EDITOR_LABEL]: 'Yangi Redaktorni Tanlang',
    [LocalizationKeys.ARTICLE_REASSIGNED_SUCCESS_MESSAGE]: 'Maqola redaktori muvaffaqiyatli qayta tayinlandi.',
    [LocalizationKeys.NO_ARTICLES_IN_SYSTEM_MESSAGE]: 'Tizimda mezonlarga mos keladigan maqolalar topilmadi.',
    [LocalizationKeys.DAYS_IN_STATUS_LABEL]: 'Holatdagi Kunlar',
    [LocalizationKeys.ARTICLE_ID_LABEL]: 'Maqola IDsi',
    [LocalizationKeys.AUTHOR_NAME_LABEL]: 'Muallif',
    [LocalizationKeys.ASSIGNED_EDITOR_LABEL]: 'Tayinlangan Redaktor',
    [LocalizationKeys.MAQOLALARNI_BOSHQARISH_ADMIN]: 'Maqolalarni Boshqarish',
    [LocalizationKeys.AUDIT_JURNALI_ADMIN]: 'Audit Jurnali',
    status_label: 'Holat',
    filter_options_title: 'Filtr Sozlamalari',
    all_action_types: 'Barcha Amal Turlari',
    start_date_label: 'Boshlanish Sanasi',
    end_date_label: 'Tugash Sanasi',
    target_entity_label: 'Nishon Obyekti',
    loading_audit_logs: 'Audit yozuvlari yuklanmoqda...',
    search_articles_title_author_label: 'Qidirish (Sarlavha, Muallif)',
    all_journals: 'Barcha Jurnallar',
    all_editors: 'Barcha Redaktorlar',
    loading_articles_overview: 'Maqolalar umumiy koʻrinishi yuklanmoqda...',
    reassign_button: 'Qayta Tayinlash',
    manage_integrations_button: 'Integratsiyalarni Boshqarish',
    in_journal_label: 'jurnalida',
    days_in_current_status: 'kun joriy holatda',
    days_short_label: 'k',
    key_not_set_placeholder: 'Kalit oʻrnatilmagan yoki yashirilgan',
    api_key_management_note: 'API Kalitini boshqarish xavfsiz tarzda amalga oshirilishi kerak, masalan, muhit oʻzgaruvchilari yoki maxfiy omborxona orqali.',
    configure_roles_button_placeholder: 'Rollarni Sozlash (Kelajakdagi Funksiya)',
    event_user_registration: 'Foydalanuvchi Roʻyxatdan Oʻtishi',
    event_article_submitted: 'Maqola Yuborildi',
    event_article_status_changed_to_reviewing: 'Maqola Holati: Koʻrib Chiqilmoqda',
    event_article_status_changed_to_needs_revision: 'Maqola Holati: Tahrirlash Kerak',
    event_article_status_changed_to_accepted: 'Maqola Holati: Qabul Qilindi',
    event_article_status_changed_to_rejected: 'Maqola Holati: Rad Etildi',
    event_article_status_changed_to_published: 'Maqola Holati: Nashr Etildi',
    event_new_message_for_author: 'Muallif Uchun Yangi Xabar',
    event_new_message_for_editor: 'Redaktor Uchun Yangi Xabar',
    event_password_reset_request: 'Parolni Tiklash Soʻrovi',
    event_issue_published: 'Nashr Chop Etildi',
    audit_action_user_login: 'Foydalanuvchi Kirishi',
    audit_action_user_created: 'Foydalanuvchi Yaratildi',
    audit_action_user_updated: 'Foydalanuvchi Yangilandi',
    audit_action_user_deleted: 'Foydalanuvchi Oʻchirildi',
    audit_action_user_role_changed: 'Foydalanuvchi Roli Oʻzgartirildi',
    audit_action_journal_created: 'Jurnal Yaratildi',
    audit_action_journal_updated: 'Jurnal Yangilandi',
    audit_action_journal_deleted: 'Jurnal Oʻchirildi',
    audit_action_article_submitted: 'Maqola Yuborildi',
    audit_action_article_status_changed: 'Maqola Holati Oʻzgartirildi',
    audit_action_article_editor_assigned: 'Maqolaga Redaktor Tayinlandi',
    audit_action_settings_updated: 'Sozlamalar Yangilandi',
    audit_action_integration_updated: 'Integratsiya Yangilandi',
    audit_action_issue_created: 'Nashr Yaratildi',
    audit_action_issue_updated: 'Nashr Yangilandi',
    audit_action_issue_published: 'Nashr Chop Etildi',
    audit_action_article_assigned_to_issue: 'Maqola Nashrga Qoʻshildi',
    [LocalizationKeys.GOOGLE_SCHOLAR_METADATA_NOTE]: 'Dasturchilar uchun eslatma: Google Scholar indeksatsiyasini yaxshilash uchun ommaviy maqola sahifalarida SEO-doʻst URL manzillari va tuzilgan metama’lumotlar (Dublin Core, Highwire Press, Schema.org) mavjudligini ta’minlang.',
    [LocalizationKeys.MANAGE_JOURNAL_ISSUES_BUTTON]: 'Nashrlarni Boshqarish',
    [LocalizationKeys.JOURNAL_ISSUE_MANAGEMENT_TITLE]: 'Jurnal Nashrlarini Boshqarish',
    [LocalizationKeys.CREATE_NEW_ISSUE_BUTTON]: 'Yangi Nashr Yaratish',
    [LocalizationKeys.ISSUE_NUMBER_LABEL]: 'Nashr Raqami / Jild',
    [LocalizationKeys.ISSUE_NUMBER_PLACEHOLDER]: 'Masalan, 1-jild, 1-son - 2024 yoki 2024-Q3',
    [LocalizationKeys.PUBLICATION_DATE_LABEL]: 'Nashr Sanasi',
    [LocalizationKeys.COVER_IMAGE_URL_LABEL]: 'Muqova Rasmi URL manzili (Ixtiyoriy)',
    [LocalizationKeys.COVER_IMAGE_URL_PLACEHOLDER]: 'https://example.com/cover.jpg',
    [LocalizationKeys.COMPILED_ISSUE_PDF_URL_LABEL]: 'Jamlanma Nashr PDF URL manzili (Ixtiyoriy)',
    [LocalizationKeys.COMPILED_ISSUE_PDF_URL_PLACEHOLDER]: 'https://example.com/issue.pdf',
    [LocalizationKeys.IS_PUBLISHED_LABEL]: 'Nashr Etilganmi?',
    [LocalizationKeys.CREATE_ISSUE_MODAL_TITLE]: 'Yangi Nashr Yaratish',
    [LocalizationKeys.EDIT_ISSUE_MODAL_TITLE]: 'Nashrni Tahrirlash',
    [LocalizationKeys.ISSUE_CREATED_SUCCESS]: 'Nashr muvaffaqiyatli yaratildi.',
    [LocalizationKeys.ISSUE_UPDATED_SUCCESS]: 'Nashr muvaffaqiyatli yangilandi.',
    [LocalizationKeys.NO_ISSUES_FOUND]: 'Ushbu jurnal uchun hali nashrlar topilmadi.',
    [LocalizationKeys.VIEW_ISSUE_DETAILS_BUTTON]: 'Tafsilotlarni Koʻrish',
    [LocalizationKeys.ARTICLES_IN_ISSUE_LABEL]: 'Ushbu nashrdagi maqolalar:',
    [LocalizationKeys.PUBLISHED_IN_ISSUE_LABEL]: 'Nashr Etilgan Joyi:',
    [LocalizationKeys.DOWNLOAD_ISSUE_BUTTON]: 'Nashrni Yuklab Olish (Soxta)',
    loading_journal_issues: 'Jurnal nashrlari yuklanmoqda...',
    journal_not_found: 'Jurnal topilmadi.',
    issue_number_date_required: 'Nashr raqami va nashr sanasi talab qilinadi.',
    confirm_delete_issue_prompt: 'Haqiqatan ham bu nashrni oʻchirmoqchimisiz?',
    issue_deleted_successfully: 'Nashr muvaffaqiyatli oʻchirildi.',
    published_status_true: 'Nashr Etilgan',
    published_status_false: 'Nashr Etilmagan',
    issue_cover_alt: '{issueNumber} uchun muqova',
    view_issue_details_placeholder: '{issueNumber} uchun tafsilotlarni koʻrish (Amalga oshirilmagan)',
    edit_button: 'Tahrirlash',
    delete_button: 'Oʻchirish',
    create_button: 'Yaratish',
    download_issue_placeholder: '{path} yuklab olish (Amalga oshirilmagan)',
    [LocalizationKeys.AI_TITLE_SUGGESTION_TITLE]: 'SI Sarlavha Taklifi',
    ai_title_suggestion_desc: "Annotatsiyangiz va kalit soʻzlaringiz asosida SI muqobil sarlavhalarni taklif qilishi mumkin.",
    [LocalizationKeys.GET_TITLE_SUGGESTIONS_BUTTON]: 'Sarlavha Takliflarini Olish (SI)',
    [LocalizationKeys.SUGGESTED_TITLES_LABEL]: 'Taklif Qilingan Sarlavhalar:',
    [LocalizationKeys.AI_SUGGESTING_TITLES]: 'SI sarlavhalarni taklif qilmoqda...',
    [LocalizationKeys.AI_ERROR_NO_TITLE_SUGGESTIONS]: 'SI hozirda sarlavha taklif qila olmadi.',
    use_this_title_button: 'Foydalanish',
    [LocalizationKeys.ARTICLE_DOI_LABEL]: 'DOI:',
    [LocalizationKeys.ARTICLE_VIEW_COUNT_LABEL]: 'Koʻrishlar:',
    [LocalizationKeys.ARTICLE_DOWNLOAD_COUNT_LABEL]: 'Yuklab Olishlar:',
    [LocalizationKeys.ARTICLE_CITATION_COUNT_LABEL]: 'Iqtiboslar:',
    [LocalizationKeys.REVIEWER_COMMENTS_TITLE]: 'Taqrizchilar Izohlari',
    [LocalizationKeys.NO_REVIEWER_COMMENTS_YET]: 'Hali taqrizchi izohlari yoʻq.',
    [LocalizationKeys.REPLY_TO_REVIEWERS_BUTTON]: 'Taqrizchiga Javob Berish',
    [LocalizationKeys.SUBMIT_REPLY_BUTTON]: 'Javobni Yuborish',
    [LocalizationKeys.YOUR_REPLY_PLACEHOLDER]: 'Taqrizchiga javobingizni kiriting...',
    reviewer_comment_label: 'Taqrizchi Izohi:',
    your_reply_label: 'Sizning Javobingiz:',
    [LocalizationKeys.REPLY_SUBMITTED_SUCCESS]: 'Javobingiz yuborildi (soxta).',
    [LocalizationKeys.FILTER_BY_DOI_LABEL]: 'DOI Boʻyicha Filtr',
    [LocalizationKeys.FILTER_BY_PUBLICATION_YEAR_LABEL]: 'Nashr Yili Boʻyicha Filtr',
    [LocalizationKeys.SORT_BY_LABEL]: 'Saralash:',
    [LocalizationKeys.SORT_BY_SUBMISSION_DATE]: 'Yuborilgan Sana',
    [LocalizationKeys.SORT_BY_CITATION_COUNT]: 'Iqtiboslar Soni',
    [LocalizationKeys.SORT_BY_VIEW_COUNT]: 'Koʻrishlar Soni',
    [LocalizationKeys.SORT_BY_DOI]: 'DOI',
    [LocalizationKeys.AI_JOURNAL_COMPLIANCE_CHECK_TITLE]: 'SI Jurnalga Muvofiqlik Tekshiruvi',
    [LocalizationKeys.AI_JOURNAL_COMPLIANCE_CHECK_DESC]: 'SI yordamida maqolangiz loyihasini tanlangan jurnalning yuborish qoidalariga muvofiqligini tekshiring.',
    [LocalizationKeys.RUN_AI_COMPLIANCE_CHECK_BUTTON]: 'SI Muvofiqlik Tekshiruvini Oʻtkazish',
    [LocalizationKeys.AI_COMPLIANCE_CHECK_RUNNING]: 'SI muvofiqlikni tekshirmoqda...',
    [LocalizationKeys.AI_COMPLIANCE_REPORT_TITLE]: 'SI Muvofiqlik Hisoboti',
    [LocalizationKeys.AI_COMPLIANCE_ITEM_MET]: 'Muvofiq',
    [LocalizationKeys.AI_COMPLIANCE_ITEM_NOT_MET]: 'Xatoliklar Topildi',
    [LocalizationKeys.AI_COMPLIANCE_ITEM_NOT_ENOUGH_INFO]: 'Yetarli Ma’lumot Yoʻq',
    [LocalizationKeys.AI_COMPLIANCE_OVERALL]: 'Umumiy Baho',
    ai_compliance_check_journal_checklist_needed: 'SI muvofiqlik tekshiruvi uchun tanlangan jurnalda belgilangan yuborish nazorat roʻyxati boʻlishi kerak.',
    ai_compliance_check_article_content_needed: 'SI muvofiqlik tekshiruvi uchun maqola annotatsiyasi yoki yuklangan fayl kerak.',
    [LocalizationKeys.SUBMISSION_TARGET_TYPE_LABEL]: 'Yuborish Maqsadi Turi',
    [LocalizationKeys.SUBMISSION_TARGET_TYPE_JOURNAL]: 'Jurnal',
    [LocalizationKeys.SUBMISSION_TARGET_TYPE_CONFERENCE]: 'Konferensiya',
    [LocalizationKeys.SUBMISSION_TARGET_TYPE_SPECIAL_ISSUE]: 'Maxsus Nashr',
    [LocalizationKeys.SUBMISSION_TARGET_DETAILS_LABEL]: 'Maqsad Tafsilotlari (masalan, Konferensiya Nomi)',
    [LocalizationKeys.SUBMISSION_TARGET_DETAILS_PLACEHOLDER]: 'Konferensiya nomini yoki maxsus nashr sarlavhasini kiriting',
    submission_target_details_required: 'Tanlangan yuborish maqsadi uchun tafsilotlar (masalan, konferensiya nomi) talab qilinadi.',
    [LocalizationKeys.JOURNAL_SELECTION_REQUIRED_ERROR]: 'Yuborish uchun jurnalni tanlang.',
    [LocalizationKeys.NOTIFY_ARTICLE_SUBMITTED_CONFIRMATION]: 'Maqola Yuborilganligi Tasdigʻi',
    [LocalizationKeys.NOTIFY_ARTICLE_ASSIGNED_TO_EDITOR]: 'Maqola Redaktorga Tayinlanganligi',
    [LocalizationKeys.NOTIFY_PEER_REVIEW_STARTED]: 'Taqriz Boshlanganligi',
    [LocalizationKeys.NOTIFY_PEER_REVIEW_COMMENT_RECEIVED]: 'Taqriz Izohi Kelganligi',
    [LocalizationKeys.NOTIFY_ARTICLE_DECISION_MADE]: 'Maqola Boʻyicha Qaror Qabul Qilinganligi (Qabul/Rad/Tahrir)',
    [LocalizationKeys.NOTIFY_ARTICLE_PUBLISHED_CONFIRMATION]: 'Maqola Nashr Etilganligi Tasdigʻi',
    [LocalizationKeys.NOTIFY_DOI_ASSIGNED_TO_ARTICLE]: 'Maqolaga DOI Tayinlanganligi',
    [LocalizationKeys.ALL_SUBMISSION_TARGETS]: 'Barcha Yuborish Maqsadlari',
    [LocalizationKeys.SUBMITTED_TO_LABEL]: 'Yuborilgan Joyi',
    [LocalizationKeys.ARTICLE_STATS_TITLE]: 'Maqola Statistikasi',
    [LocalizationKeys.DOI_PROVIDER_SETTINGS_TITLE]: 'DOI Provayderi Sozlamalari',
    [LocalizationKeys.DOI_PROVIDER_NAME_LABEL]: 'Provayder Nomi',
    [LocalizationKeys.DOI_API_KEY_LABEL]: 'API Kaliti',
    [LocalizationKeys.DOI_API_SECRET_LABEL]: 'API Maxfiy Kaliti (agar mavjud boʻlsa)',
    [LocalizationKeys.DOI_PREFIX_LABEL]: 'DOI Prefiksi',
    [LocalizationKeys.MANAGE_DOI_TITLE]: 'DOIni Boshqarish',
    [LocalizationKeys.ASSIGN_GENERATE_DOI_BUTTON]: 'DOI Tayinlash/Yaratish',
    [LocalizationKeys.DOI_ASSIGNED_SUCCESS]: 'DOI muvaffaqiyatli tayinlandi.',
    [LocalizationKeys.DOI_STATUS_LABEL]: 'Joriy DOI',
    doi_input_required_error: 'DOI qiymati talab qilinadi.',
    doi_already_assigned_note: 'DOI tayinlangan. Oʻzgartirish uchun administratorga murojaat qiling.',
    [LocalizationKeys.PUBLIC_SEARCH_PAGE_TITLE]: 'Nashrlarni Qidirish',
    [LocalizationKeys.SEARCH_ARTICLES_PLACEHOLDER]: 'Sarlavha, kalit soʻzlar, muallif, DOI boʻyicha qidirish...',
    [LocalizationKeys.SEARCH_BUTTON]: 'Qidirish',
    [LocalizationKeys.NO_SEARCH_RESULTS]: 'Sizning soʻrovingiz boʻyicha natijalar topilmadi.',
    [LocalizationKeys.SEARCH_RESULTS_FOR_LABEL]: 'Qidiruv Natijalari:',
    [LocalizationKeys.VIEW_ARTICLE_BUTTON]: 'Maqolani Koʻrish',
    view_article_button_action_placeholder: '{id} toʻliq maqolasini koʻrish (amalga oshirilmagan)',
    go_back_button: 'Ortga Qaytish',
    [LocalizationKeys.ADMIN_SEARCH_SETTINGS_TITLE]: 'Qidiruv Indeksi Sozlamalari',
    [LocalizationKeys.REINDEX_SEARCH_BUTTON]: 'Qidiruv Mazmunini Qayta Indekslash',
    [LocalizationKeys.SHARE_ARTICLE_BUTTON]: 'Ulashish',
    sharing_options_for_article: 'Ulashish imkoniyatlari:',
    searching_articles: 'Maqolalar qidirilmoqda...',
    [LocalizationKeys.GENERATE_ISSUE_PDF_BUTTON]: 'Nashr PDFini Yaratish',
    [LocalizationKeys.ISSUE_PDF_GENERATION_IN_PROGRESS]: 'PDF yaratilmoqda...',
    [LocalizationKeys.ISSUE_PDF_GENERATED_SUCCESS]: 'Nashr PDFi muvaffaqiyatli yaratildi (soxta).',
    [LocalizationKeys.VIEW_GENERATED_PDF_BUTTON]: 'Yaratilgan PDFni Koʻrish',
    [LocalizationKeys.CONFIRM_ISSUE_PDF_BUTTON]: 'PDFni Tasdiqlash va Nashr Etish',
    compiled_pdf_available_label: 'Jamlanma PDF:',
    [LocalizationKeys.DIGITALLY_SIGN_SUBMISSION_CHECKBOX]: 'Ushbu Yuborishni Raqamli Imzolash (soxta)',
    [LocalizationKeys.DIGITAL_SIGNATURE_STATUS_LABEL]: 'Raqamli Imzo:',
    [LocalizationKeys.SIGNATURE_STATUS_PENDING]: 'Imzolanish Kutilmoqda',
    [LocalizationKeys.SIGNATURE_STATUS_SIGNED]: 'Imzolangan',
    [LocalizationKeys.SIGNATURE_STATUS_ERROR]: 'Imzolashda Xatolik',
    [LocalizationKeys.SIGNATURE_STATUS_VERIFIED]: 'Tasdiqlangan',
    [LocalizationKeys.VERIFY_SIGNATURE_BUTTON]: 'Imzoni Tasdiqlash',
    [LocalizationKeys.SIGNATURE_VERIFICATION_INITIATED]: 'Imzoni tasdiqlash jarayoni boshlandi (soxta)',
    signature_status_not_available: 'Mavjud Emas',
    signature_status_unknown: 'Noma’lum',
    [LocalizationKeys.MY_ACHIEVEMENTS_TITLE]: 'Mening Yutuqlarim',
    [LocalizationKeys.AUTHOR_LEVEL_LABEL]: 'Mualliflik Darajasi:',
    [LocalizationKeys.AUTHOR_LEVEL_NEW]: 'Yangi Muallif',
    [LocalizationKeys.AUTHOR_LEVEL_ACTIVE]: 'Faol Muallif',
    [LocalizationKeys.AUTHOR_LEVEL_PRESTIGIOUS]: 'Nufuzli Muallif',
    [LocalizationKeys.BADGES_LABEL]: 'Nishonlar:',
    [LocalizationKeys.BADGE_FIRST_ARTICLE_NAME]: 'Birinchi Maqola',
    [LocalizationKeys.BADGE_FAST_EDIT_NAME]: 'Tezkor Redaktor',
    [LocalizationKeys.BADGE_INTERNATIONAL_AUTHOR_NAME]: 'Xalqaro Olim',
    [LocalizationKeys.BADGE_TOP_REVIEWER_NAME]: 'Eng Yaxshi Taqrizchi',
    [LocalizationKeys.BADGE_MULTILINGUAL_MASTER_NAME]: 'Koʻp Tilli Usta',
    [LocalizationKeys.BADGE_CONSISTENT_CONTRIBUTOR_NAME]: 'Doimiy Hissa Qoʻshuvchi',
    [LocalizationKeys.BADGE_PEER_REVIEW_PRO_NAME]: 'Professional Taqrizchi',
    [LocalizationKeys.EDITORIAL_STATS_TITLE]: 'Mening Redaktorlik Statistikam',
    [LocalizationKeys.ARTICLES_REVIEWED_LABEL]: 'Koʻrib Chiqilgan Maqolalar:',
    [LocalizationKeys.AVG_REVIEW_TIME_LABEL]: 'Oʻrtacha Koʻrib Chiqish Vaqti:',
    [LocalizationKeys.VIEW_RANKINGS_BUTTON]: 'Reytinglarni Koʻrish',
    [LocalizationKeys.PUBLIC_RANKINGS_PAGE_TITLE]: 'Platforma Reytinglari',
    [LocalizationKeys.RANKINGS_TOP_AUTHORS_TITLE]: 'Eng Yaxshi Mualliflar',
    [LocalizationKeys.RANKINGS_TOP_EDITORS_TITLE]: 'Eng Yaxshi Redaktorlar',
    [LocalizationKeys.RANKINGS_TOP_JOURNALS_TITLE]: 'Eng Yaxshi Jurnallar',
    [LocalizationKeys.RANK_LABEL]: 'Oʻrin',
    [LocalizationKeys.SCORE_LABEL]: 'Ball',
    [LocalizationKeys.NO_RANKING_DATA]: 'Hozirda reyting ma’lumotlari mavjud emas.',
    loading_rankings: 'Reytinglar yuklanmoqda...',
    [LocalizationKeys.NAV_CALENDAR]: 'Taqvim',
    [LocalizationKeys.CALENDAR_PAGE_TITLE]: 'Shaxsiy Taqvim va Rejalashtiruvchi',
    [LocalizationKeys.ADD_NEW_TASK_BUTTON]: 'Yangi Vazifa Qoʻshish',
    [LocalizationKeys.TASK_LIST_TITLE]: 'Mening Vazifalarim',
    [LocalizationKeys.NO_TASKS_MESSAGE]: 'Hali vazifalar yoʻq. Birortasini qoʻshing!',
    [LocalizationKeys.TASK_MODAL_TITLE_ADD]: 'Yangi Vazifa Qoʻshish',
    [LocalizationKeys.TASK_MODAL_TITLE_EDIT]: 'Vazifani Tahrirlash',
    [LocalizationKeys.TASK_DESCRIPTION_LABEL]: 'Vazifa Tavsifi',
    [LocalizationKeys.DUE_DATE_LABEL]: 'Bajarish Muddati',
    [LocalizationKeys.RELATED_ARTICLE_LABEL]: 'Bogʻliq Maqola (Ixtiyoriy)',
    [LocalizationKeys.MARK_AS_COMPLETE_BUTTON]: 'Bajarilgan Deb Belgilash',
    [LocalizationKeys.MARK_AS_INCOMPLETE_BUTTON]: 'Bajarilmagan Deb Belgilash',
    [LocalizationKeys.SAVE_TASK_BUTTON]: 'Vazifani Saqlash',
    [LocalizationKeys.CALENDAR_EVENTS_TITLE]: 'Taqvimdagi Voqealar',
    [LocalizationKeys.ARTICLE_DEADLINE_EVENT]: 'Maqola Muddati',
    [LocalizationKeys.SYSTEM_REMINDER_EVENT]: 'Tizim Eslatmasi',
    [LocalizationKeys.TASK_COMPLETED_SUCCESS]: 'Vazifa bajarilgan deb belgilandi.',
    [LocalizationKeys.TASK_INCOMPLETE_SUCCESS]: 'Vazifa bajarilmagan deb belgilandi.',
    [LocalizationKeys.TASK_SAVED_SUCCESS]: 'Vazifa muvaffaqiyatli saqlandi.',
    [LocalizationKeys.TASK_DELETED_SUCCESS]: 'Vazifa muvaffaqiyatli oʻchirildi.',
    [LocalizationKeys.CONFIRM_DELETE_TASK_PROMPT]: 'Haqiqatan ham bu vazifani oʻchirmoqchimisiz?',
    [LocalizationKeys.MONTH_PREVIOUS]: 'Oldingi',
    [LocalizationKeys.MONTH_NEXT]: 'Keyingi',
    [LocalizationKeys.DELETE_TASK_BUTTON]: 'Vazifani Oʻchirish',
    [LocalizationKeys.EDITOR_FILTER_BY_JOURNAL_LABEL]: 'Jurnal Boʻyicha Filtr',
    [LocalizationKeys.EDITOR_FILTER_BY_AUTHOR_NAME_LABEL]: 'Muallif Ismi Boʻyicha Filtr',
    [LocalizationKeys.EDITOR_FILTER_BY_SUBMISSION_DATE_RANGE_LABEL]: 'Yuborilgan Sana Oraligʻi',
    [LocalizationKeys.EDITOR_FILTER_BY_MIN_PLAGIARISM_LABEL]: 'Minimal Plagiat Foizi (%)',
    [LocalizationKeys.EDITOR_SORT_BY_LABEL]: 'Saralash',
    [LocalizationKeys.EDITOR_SORT_SUBMISSION_DATE_NEWEST]: 'Yuborilgan Sana (Eng Yangi)',
    [LocalizationKeys.EDITOR_SORT_SUBMISSION_DATE_OLDEST]: 'Yuborilgan Sana (Eng Eski)',
    [LocalizationKeys.EDITOR_SORT_TITLE_ASC]: 'Sarlavha (A-Z)',
    [LocalizationKeys.EDITOR_SORT_TITLE_DESC]: 'Sarlavha (Z-A)',
    [LocalizationKeys.EDITOR_SORT_LAST_UPDATE_NEWEST]: 'Oxirgi Yangilanish (Eng Yangi)',
    [LocalizationKeys.EDITOR_SORT_LAST_UPDATE_OLDEST]: 'Oxirgi Yangilanish (Eng Eski)',
    [LocalizationKeys.ALL_MY_JOURNALS]: 'Barcha Jurnallarim',
    [LocalizationKeys.MIN_PLAGIARISM_PLACEHOLDER]: 'Masalan, 10',
    [LocalizationKeys.AI_SUGGESTIONS_MODAL_TITLE]: 'SI Grammatika va Uslub Takliflari',
    [LocalizationKeys.GRAMMAR_ISSUES_SUGGESTIONS_LABEL]: 'Grammatik Xatolar va Takliflar',
    [LocalizationKeys.STYLE_SUGGESTIONS_LABEL]: 'Uslubiy Takliflar',
    [LocalizationKeys.NO_GRAMMAR_ISSUES_FOUND]: 'SI tomonidan aniq grammatik xatolar topilmadi.',
    [LocalizationKeys.NO_STYLE_SUGGESTIONS_FOUND]: 'SI tomonidan aniq uslubiy takliflar topilmadi.',
    [LocalizationKeys.AI_CHECK_NOT_PERFORMED_OR_UNAVAILABLE]: 'SI tekshiruvi oʻtkazilmagan yoki ma’lumotlar mavjud emas.',
    [LocalizationKeys.AI_CHECK_STATUS_PASSED]: 'Oʻtdi',
    [LocalizationKeys.AI_CHECK_STATUS_PASSED_WITH_SUGGESTIONS]: 'Takliflar bilan oʻtdi',
    [LocalizationKeys.AI_CHECK_STATUS_ISSUES_FOUND]: 'Xatoliklar topildi',
    [LocalizationKeys.AI_CHECK_STATUS_ERROR]: 'SI tekshiruvi paytida xatolik',
    overall_summary_label: 'Umumiy Xulosa:',
    checked_on_date_label: 'Tekshirilgan Sana:',
    close_button: 'Yopish',
    select_journal_placeholder: '-- Jurnalni Tanlang --',
    select_an_article_optional: 'Maqolani Tanlang (Ixtiyoriy)',
    notes_for_developers: 'Dasturchilar Uchun Eslatmalar',
    journal_selected_from_ai_suggestion: "'{journalName}' jurnali SI taklifi asosida tanlandi.",
    ai_suggested_journal_not_in_list: "SI taklif qilgan '{journalName}' jurnali joriy roʻyxatda mavjud emas. Iltimos, tekshiring yoki qoʻlda qoʻshing.",
    xizmatlar: 'Xizmatlar',
    [LocalizationKeys.SUGGEST_TITLE_AI_BUTTON]: 'SI Bilan Taklif',
    [LocalizationKeys.SUGGEST_KEYWORDS_AI_BUTTON]: 'SI Bilan Taklif',
    [LocalizationKeys.SUGGEST_JOURNALS_AI_BUTTON]: 'SI Bilan Taklif',
    [LocalizationKeys.USE_SUGGESTED_TITLE_BUTTON]: 'Foydalanish',
    [LocalizationKeys.ADD_SUGGESTED_KEYWORD_BUTTON]: 'Qoʻshish +',
    [LocalizationKeys.SELECT_SUGGESTED_JOURNAL_BUTTON]: 'Tanlash',
    [LocalizationKeys.AI_ERROR_NO_SUGGESTIONS]: 'SI hozirda taklif bera olmadi.',
    [LocalizationKeys.AI_FETCHING_SUGGESTIONS]: 'SI takliflarni olmoqda...',
    [LocalizationKeys.AI_SUGGESTING_KEYWORDS]: 'SI kalit soʻzlarni taklif qilmoqda...',
    [LocalizationKeys.PLAGIARISM_SERVICE_CONFIGURATION_TITLE]: 'Plagiat Xizmati Konfiguratsiyasi',
    [LocalizationKeys.PLAGIARISM_CHECK_DETAILS_CARD_TITLE]: 'Plagiat Tekshiruvi Tafsilotlari',
    [LocalizationKeys.PLAGIARISM_SERVICE_URL_LABEL]: 'Xizmat URL manzili',
    [LocalizationKeys.PLAGIARISM_MONTHLY_LIMIT_LABEL]: 'Oylik Tekshiruv Chegarasi',
    [LocalizationKeys.PLAGIARISM_ADVANCED_SETTINGS_LINK_LABEL]: 'Kengaytirilgan Sozlamalar (Tashqi Havola)',
    [LocalizationKeys.RERUN_PLAGIARISM_CHECK_BUTTON]: 'Plagiat Tekshiruvini Qayta Oʻtkazish',
    [LocalizationKeys.PLAGIARISM_CHECK_SUCCESS_RERUN]: 'Plagiat tekshiruvi qayta oʻtkazish muvaffaqiyatli boshlandi.',
    [LocalizationKeys.NAV_AI_DOCUMENT_UTILITIES]: 'SI Hujjat Yordamchisi',
    [LocalizationKeys.AI_DOCUMENT_UTILITIES_PAGE_TITLE]: 'SI Hujjat Yordamchilari',
    [LocalizationKeys.LITERACY_CHECK_SECTION_TITLE]: 'SI Savodxonlik va Grammatika Tekshiruvi',
    [LocalizationKeys.TRANSLITERATION_SECTION_TITLE]: 'SI Kirill/Lotin Transliteratsiyasi',
    [LocalizationKeys.UPLOAD_PDF_FOR_ANALYSIS_LABEL]: 'Savodxonlik Tahlili uchun PDF Yuklash',
    [LocalizationKeys.UPLOAD_PDF_FOR_TRANSLITERATION_LABEL]: 'Transliteratsiya uchun PDF Yuklash',
    [LocalizationKeys.ANALYZE_DOCUMENT_BUTTON]: 'Hujjatni Tahlil Qilish',
    [LocalizationKeys.TRANSLITERATE_DOCUMENT_BUTTON]: 'Hujjatni Transliteratsiya Qilish',
    [LocalizationKeys.SELECT_TRANSLITERATION_DIRECTION_LABEL]: 'Transliteratsiya Yoʻnalishini Tanlang',
    [LocalizationKeys.CYRILLIC_TO_LATIN]: 'Kirilldan Lotinga',
    [LocalizationKeys.LATIN_TO_CYRILLIC]: 'Lotindan Kirillga',
    [LocalizationKeys.LITERACY_REPORT_TITLE]: 'SI Savodxonlik Hisoboti',
    [LocalizationKeys.LITERACY_SUGGESTIONS_TITLE]: 'Yaxshilash Uchun Takliflar',
    [LocalizationKeys.TRANSLITERATED_TEXT_TITLE]: 'Transliteratsiya Qilingan Matn',
    [LocalizationKeys.PROCESSING_LITERACY_CHECK]: 'SI hujjatingizni savodxonlik uchun tahlil qilmoqda...',
    [LocalizationKeys.PROCESSING_TRANSLITERATION]: 'SI hujjatingizni transliteratsiya qilmoqda...',
    [LocalizationKeys.ERROR_PROCESSING_PDF]: 'PDF faylni qayta ishlashda xatolik yuz berdi.',
    [LocalizationKeys.ERROR_NO_FILE_SELECTED]: 'Iltimos, avval fayl tanlang.',
    [LocalizationKeys.COPY_TEXT_BUTTON]: 'Matndan nusxa olish',
    [LocalizationKeys.DOWNLOAD_TEXT_BUTTON]: 'Matnni yuklab olish',
    [LocalizationKeys.PDF_ANALYSIS_DESCRIPTION]: "PDF hujjatingizni yuklang va SI uning savodxonligi, uslubi va grammatikasini tahlil qilsin. Bu ilmiy matnlaringiz sifatini yaxshilashga yordam beradi.",
    [LocalizationKeys.TRANSLITERATION_DESCRIPTION]: "SI yordamida PDF hujjatlaringizdagi matnlarni Kirill alifbosidan Lotinga yoki aksincha oʻgiring. Hujjatni yuklang, yoʻnalishni tanlang va natijani oling.",
    [LocalizationKeys.PDF_TEXT_EXTRACTION_SIMULATION_NOTE]: 'Eslatma: Bu funksiya PDF-dan matn chiqarishni simulyatsiya qiladi. Haqiqiy natijalar hujjatning murakkabligiga bogʻliq.',
    [LocalizationKeys.TEXT_COPIED_SUCCESS]: 'Matndan nusxa olindi!',
    [LocalizationKeys.TEXT_DOWNLOAD_STARTED]: 'Matnni yuklab olish boshlandi.',
    [LocalizationKeys.FOOTER_CDC_CREDIT]: 'CDCGroup tomonidan ilmiy asosda ishlab chiqildi',
    [LocalizationKeys.FOOTER_CRADEV_CREDIT]: 'CraDev Company texnologik hamkorligida',
    [LocalizationKeys.NAV_PLAGIARISM_CHECKER]: 'Plagiat Tekshiruvi',
    [LocalizationKeys.PLAGIARISM_CHECKER_PAGE_TITLE]: 'Plagiat va SI Kontent Tekshiruvi',
    [LocalizationKeys.UPLOAD_DOCUMENT_FOR_PLAGIARISM_CHECK_LABEL]: 'Plagiat tekshiruvi uchun hujjatni yuklang',
    [LocalizationKeys.RUN_PLAGIARISM_CHECK_BUTTON_GENERIC]: 'Plagiat Tekshiruvini Boshlash',
    [LocalizationKeys.PLAGIARISM_RESULT_SECTION_TITLE]: 'Plagiat Tekshiruvi Natijasi',
    [LocalizationKeys.SIMILARITY_PERCENTAGE_DISPLAY]: 'Oʻxshashlik foizi',
    [LocalizationKeys.CERTIFICATE_ELIGIBLE_MESSAGE]: 'Tabriklaymiz! Hujjatingiz sertifikat uchun talablarga javob beradi.',
    [LocalizationKeys.CERTIFICATE_NOT_ELIGIBLE_MESSAGE]: 'Hujjatning oʻxshashlik darajasi ({percentage}%) juda yuqori.',
    [LocalizationKeys.DOWNLOAD_PLAGIARISM_CERTIFICATE_BUTTON]: 'Plagiat Sertifikatini Yuklab Olish',
    [LocalizationKeys.CERTIFICATE_DOWNLOAD_PROMPT]: 'Sertifikatni yuklab olish (soxta)',
    [LocalizationKeys.ERROR_NO_FILE_FOR_PLAGIARISM_CHECK]: 'Plagiat tekshiruvi uchun fayl tanlanmagan.',
    [LocalizationKeys.ERROR_DURING_PLAGIARISM_CHECK]: 'Plagiat tekshiruvi paytida xatolik yuz berdi',
    [LocalizationKeys.CHECKING_PLAGIARISM_MESSAGE]: 'Plagiat tekshirilmoqda, iltimos kuting...',
    [LocalizationKeys.PLAGIARISM_CHECK_THRESHOLD_NOTE]: `Eslatma: Ushbu soxta tizimda klirens sertifikati uchun odatda o'xshashlik darajasi ${PLAGIARISM_CERTIFICATE_THRESHOLD}% dan past va SI kontent ehtimoli ${AI_CONTENT_CERTIFICATE_THRESHOLD}% dan past bo'lishi maqbul deb hisoblanadi.`,
    [LocalizationKeys.AI_CONTENT_PROBABILITY_LABEL]: 'SI Kontent Ehtimoli',
    [LocalizationKeys.AI_CONTENT_ANALYSIS_SECTION_TITLE]: 'SI Kontent Tahlili',
    [LocalizationKeys.VIEW_AI_ANALYSIS_REPORT_BUTTON]: 'SI Tahlili Hisobotini Koʻrish',
    [LocalizationKeys.AI_ANALYSIS_REPORT_MODAL_TITLE]: 'SI Kontent Tahlili Hisoboti (Namuna)',
    [LocalizationKeys.AI_ANALYSIS_REPORT_INTRO_LABEL]: 'Bu SI kontent tahlilining namunaviy hisoboti.',
    [LocalizationKeys.AI_ANALYSIS_SECTION_LABEL]: 'Boʻlim',
    [LocalizationKeys.AI_ANALYSIS_ASSESSMENT_LABEL]: 'Baho',
    [LocalizationKeys.AI_ANALYSIS_EVIDENCE_LABEL]: 'Dalil',
    [LocalizationKeys.CERTIFICATE_NOT_ELIGIBLE_AI_CONTENT]: 'SI kontent ehtimoli ({ai_percentage}%) juda yuqori.',
    [LocalizationKeys.PLAGIARISM_AND_AI_CHECKER_PAGE_TITLE]: 'Plagiat va SI Kontent Tekshiruvi',
    [LocalizationKeys.PAYMENT_CONFIRMATION_TITLE]: 'Toʻlovni Tasdiqlash',
    [LocalizationKeys.PAYMENT_CONFIRMATION_MESSAGE]: 'Plagiat tekshiruvi xizmati uchun toʻlov {price} UZS. Davom etishga rozimisiz?',
    [LocalizationKeys.PAYMENT_AGREE_BUTTON]: 'Roziman va Davom Etish',
    [LocalizationKeys.PAYMENT_DETAILS_TITLE]: 'Toʻlov Tafsilotlari',
    [LocalizationKeys.PLASTIC_CARD_NUMBER_LABEL]: 'Toʻlov uchun plastik karta raqami',
    [LocalizationKeys.MOCK_PLASTIC_CARD_NUMBER]: '8600 1234 5678 9012',
    [LocalizationKeys.UPLOAD_RECEIPT_LABEL]: 'Toʻlov kvitansiyasini yuklang (skrinshot)',
    [LocalizationKeys.SEND_BUTTON]: 'Yuborish',
    [LocalizationKeys.PAYMENT_SUBMITTED_MESSAGE]: 'Toʻlovingiz qabul qilindi va ma’mur tomonidan koʻrib chiqilmoqda. Natijalar tayyor boʻlganda sizga xabar beriladi.',
    [LocalizationKeys.RECEIPT_REQUIRED_ERROR]: 'Iltimos, toʻlov kvitansiyasini yuklang.',
    [LocalizationKeys.ERROR_PAYMENT_FIRST]: 'Tekshiruvni boshlashdan oldin toʻlovni amalga oshirish kerak.',
    [LocalizationKeys.NOTIFICATION_BELL_ARIA_LABEL]: 'Bildirishnomalarni koʻrish',
    [LocalizationKeys.NOTIFICATIONS_TITLE]: 'Bildirishnomalar',
    [LocalizationKeys.NO_NOTIFICATIONS]: 'Yangi bildirishnomalar yoʻq.',
    [LocalizationKeys.NOTIFICATION_PLAGIARISM_RESULTS_READY]: 'Plagiat tekshiruvi natijalari tayyor!',
    [LocalizationKeys.NOTIFICATION_ARTICLE_SUBMISSION_PAYMENT_APPROVED]: 'Maqola yuborish uchun toʻlovingiz tasdiqlandi. Maqolangiz koʻrib chiqishga yuborildi.',
    [LocalizationKeys.MARK_AS_READ]: 'Oʻqilgan deb belgilash',
    [LocalizationKeys.MARK_ALL_AS_READ]: 'Barchasini oʻqilgan deb belgilash',
    [LocalizationKeys.CHECK_HISTORY_TITLE]: 'Tekshiruvlar Tarixi',
    [LocalizationKeys.HISTORY_DATE_COLUMN]: 'Sana',
    [LocalizationKeys.HISTORY_FILENAME_COLUMN]: 'Fayl Nomi',
    [LocalizationKeys.HISTORY_SIMILARITY_COLUMN]: 'Oʻxshashlik (%)',
    [LocalizationKeys.HISTORY_AI_CONTENT_COLUMN]: 'SI Kontent (%)',
    [LocalizationKeys.HISTORY_STATUS_COLUMN]: 'Holat',
    [LocalizationKeys.HISTORY_NO_CHECKS_YET]: 'Hali tekshiruvlar oʻtkazilmagan.',
    [LocalizationKeys.HISTORY_STATUS_PAYMENT_PENDING_USER_ACTION]: 'Toʻlov Kutilmoqda',
    [LocalizationKeys.HISTORY_STATUS_PAYMENT_CONFIRMATION_PENDING]: 'Toʻlov Tasdiqlanishi Kutilmoqda',
    [LocalizationKeys.HISTORY_STATUS_PAYMENT_DETAILS_PENDING]: 'Toʻlov Tafsilotlari Kutilmoqda',
    [LocalizationKeys.HISTORY_STATUS_PAYMENT_PENDING_ADMIN_APPROVAL]: 'Ma’mur Tasdiqlashi Kutilmoqda',
    [LocalizationKeys.HISTORY_STATUS_PAYMENT_APPROVED_PROCESSING]: 'Tekshiruv Bajarilmoqda',
    [LocalizationKeys.HISTORY_STATUS_RESULTS_READY]: 'Natijalar Tayyor',
    [LocalizationKeys.ARTICLE_SUBMISSION_PAYMENT_CONFIRMATION_TITLE]: 'Maqola Yuborish Toʻlovini Tasdiqlash',
    [LocalizationKeys.ARTICLE_SUBMISSION_PAYMENT_CONFIRMATION_MESSAGE]: 'Maqola yuborish xizmati uchun toʻlov {price} UZS. Davom etishga rozimisiz?',
    [LocalizationKeys.ARTICLE_SUBMISSION_PAYMENT_DETAILS_TITLE]: 'Maqola Yuborish Toʻlov Tafsilotlari',
    [LocalizationKeys.ARTICLE_SUBMISSION_PAYMENT_SUBMITTED_MESSAGE]: 'Toʻlovingiz qabul qilindi. Ma’mur tasdiqlaganidan soʻng maqolangiz koʻrib chiqishga yuboriladi.',
    [LocalizationKeys.ARTICLE_SUBMITTED_SUCCESS_AFTER_PAYMENT]: 'Maqola koʻrib chiqish uchun muvaffaqiyatli yuborildi! Holatini "Mening Maqolalarim" sahifasida kuzatib boring.',
    [LocalizationKeys.NAV_FINANCIAL_OVERVIEW]: 'Moliyaviy Hisobot',
    [LocalizationKeys.FINANCIAL_OVERVIEW_TITLE]: 'Moliyaviy Hisobot',
    [LocalizationKeys.TOTAL_REVENUE]: 'Jami Daromad',
    [LocalizationKeys.PAID_SUBMISSIONS_COUNT]: 'Toʻlangan Yuborishlar Soni',
    [LocalizationKeys.AVERAGE_REVENUE_PER_SUBMISSION]: 'Har bir Yuborishdan Oʻrtacha Daromad',
    [LocalizationKeys.TRANSACTION_HISTORY]: 'Tranzaksiyalar Tarixi',
    [LocalizationKeys.TRANSACTION_ID]: 'Tranzaksiya IDsi',
    [LocalizationKeys.PAYMENT_DATE]: 'Toʻlov Sanasi',
    [LocalizationKeys.AMOUNT]: 'Summa',
    [LocalizationKeys.PAYMENT_FOR_ARTICLE]: 'Maqola uchun toʻlov',
    [LocalizationKeys.NO_TRANSACTIONS_FOUND]: 'Tranzaksiyalar topilmadi.',
    bosma_nashrlar: 'Bosma nashrlar',
    based_on_mock_data: 'Soxta ma\'lumotlarga asoslangan',
    mock_successful_payments: 'Soxta muvaffaqiyatli to\'lovlar',
  }
};
